---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
	[1] = {
		["天降财宝1"] = {
			["key_name"]="天降财宝1",
			["map_id"]="hd_tjcb",
			["activeName"]="天降财宝",
			["class"]="ActivityMapLogic",
			["openDay"]=0,
			["runType"]="MIN",
			["is_release"]=1,
			["starttime"]=10,
			["stoptime"]=20, 
			["tip_desc"]="【天降财宝】，第一波天降财宝已经发放，海量道具免费获得!", 
		},
		["天降财宝2"] = {
			["key_name"]="天降财宝2",
			["map_id"]="hd_tjcb",
			["activeName"]="天降财宝",
			["class"]="ActivityMapLogic",
			["openDay"]=0,
			["runType"]="MIN",
			["is_release"]=1,
			["starttime"]=45,
			["stoptime"]=55, 
			["tip_desc"]="【天降财宝】，第一波天降财宝已经发放，海量道具免费获得!", 
		},
		["财富广场1"] = {
			["key_name"]="财富广场1",
			["map_id"]="hd_cfgc",
			["activeName"]="财富广场",
			["class"]="ActivityMapLogic",
			["openDay"]=0,
			["runType"]="MIN",
			["is_release"]=1,
			["starttime"]=30,
			["stoptime"]=60, 
			["tip_desc"]="【财富广场】活动开放，掉落大量经验、货币、材料道具，鸡王可掉落高级物品！", 
		},
		["财富广场2"] = {
			["key_name"]="财富广场2",
			["map_id"]="hd_cfgc",
			["activeName"]="财富广场",
			["class"]="ActivityMapLogic",
			["openDay"]=0,
			["runType"]="MIN",
			["is_release"]=1,
			["starttime"]=75,
			["stoptime"]=105, 
			["tip_desc"]="【财富广场】活动开放，掉落大量经验、货币、材料道具，鸡王可掉落高级物品！", 
		},
		["行会争霸1"] = {
			["key_name"]="行会争霸1",
			["map_id"]="hd_hhzb",
			["activeName"]="行会争霸",
			["class"]="ActivityMapLogic",
			["openDay"]=0,
			["runType"]="MIN",
			["is_release"]=1,
			["starttime"]=90,
			["stoptime"]=105, 
			["tip_desc"]="【行会争霸】活动开放，宗师神龙已出现在地图，必定掉落火龙装备！", 
		},
		["天下第一1"] = {
			["key_name"]="天下第一1",
			["map_id"]="txzl",
			["activeName"]="天下第一",
			["class"]="ActivityMapLogic",
			["openDay"]=0,
			["runType"]="MIN",
			["is_release"]=1,
			["starttime"]=120,
			["stoptime"]=135, 
			["tip_desc"]="【天下第一】活动开放，限时15分钟内可前往天下之路争夺天下第一称号!", 
		},
		
		["激情夺宝1"] = {
			["key_name"]="激情夺宝1",
			["map_id"]="hd_jqdb",
			["activeName"]="激情夺宝",
			["class"]="ActivityMapLogic",
			["openDay"]=0,
			["runType"]="MIN",
			["is_release"]=1,
			["starttime"]=150,
			["stoptime"]=165, 
			["tip_desc"]="【激情夺宝】活动开放，击杀撒旦魔王必爆撒旦宝箱，持有宝箱5分钟即可获得宝箱奖励!", 
		},
		["乱斗之王1"] = {
			["key_name"]="乱斗之王1",
			["map_id"]="hd_ldzw",
			["activeName"]="乱斗之王",
			["class"]="ActivityMapLogic",
			["openDay"]=0,
			["runType"]="MIN",
			["is_release"]=1,
			["starttime"]=240,
			["stoptime"]=255, 
			["tip_desc"]="【乱斗之王】活动开放，生存值排名前三者可获得【乱斗之王】限时称号奖励!", 
		},
		["双倍押镖活动1"] = {
			["key_name"]="双倍押镖活动1",
			["map_id"]="hd_sbyb",
			["activeName"]="福威镖局",
			["class"]="EscortAgencyNpc",
			["double"]=true,
			["openDay"]=0,
			["runType"]="MIN",
			["is_release"]=1,
			["starttime"]=20,
			["stoptime"]=30, 
			["tip_desc"]="《双倍押镖》已经开放，完成押镖即可获得双倍收益，入口5分钟后关闭！", 
		},
		["双倍押镖活动2"] = {
			["key_name"]="双倍押镖活动2",
			["map_id"]="hd_sbyb",
			["activeName"]="福威镖局",
			["class"]="EscortAgencyNpc",
			["double"]=true,
			["openDay"]=0,
			["runType"]="MIN",
			["is_release"]=1,
			["starttime"]=60,
			["stoptime"]=70, 
			["tip_desc"]="《双倍押镖》已经开放，完成押镖即可获得双倍收益，入口5分钟后关闭！", 
		},  
	},
	[2] = {
		["行会争霸2"] = {
			 ["key_name"]="行会争霸2",
			["map_id"]="hd_hhzb",
			["activeName"]="行会争霸",
			["class"]="ActivityMapLogic",
			["openDay"]=1,
			["runType"]="RunOnDay",
			["starttime"]="18:30:00",
			["stoptime"]="19:00:00", 
			["tip_desc"]="【行会争霸】活动开放，宗师神龙已出现在地图，必定掉落火龙装备！", 
		},
		["天下第一2"] = {
				["key_name"]="天下第一2",
				["map_id"]="txzl",
				["activeName"]="天下第一",
				["class"]="ActivityMapLogic",
				["openDay"]=1,
				["runType"]="RunOnDay",
				["starttime"]="10:00:00",
				["stoptime"]="10:15:00", 
				["tip_desc"]="【天下第一】活动开放，限时15分钟内可前往天下之路争夺天下第一称号!", 
		},
		["天下第一3"] = {
			["key_name"]="天下第一3",
			["map_id"]="txzl",
			["activeName"]="天下第一",
			["class"]="ActivityMapLogic",
			["openDay"]=1,
			["runType"]="RunOnDay",
			["starttime"]="14:00:00",
			["stoptime"]="14:15:00", 
			["tip_desc"]="【天下第一】活动开放，限时15分钟内可前往天下之路争夺天下第一称号!", 
		},
		["天下第一4"] = {
			["key_name"]="天下第一4",
			["map_id"]="txzl",
			["activeName"]="天下第一",
			["class"]="ActivityMapLogic",
			["openDay"]=1,
			["runType"]="RunOnDay",
			["starttime"]="18:00:00",
			["stoptime"]="18:15:00", 
			["tip_desc"]="【天下第一】活动开放，限时15分钟内可前往天下之路争夺天下第一称号!", 
		},
		["天下第一5"] = {
			["key_name"]="天下第一5",
			["map_id"]="txzl",
			["activeName"]="天下第一",
			["class"]="ActivityMapLogic",
			["openDay"]=1,
			["runType"]="RunOnDay",
			["starttime"]="22:00:00",
			["stoptime"]="22:15:00", 
			["tip_desc"]="【天下第一】活动开放，限时15分钟内可前往天下之路争夺天下第一称号!", 
		},
		["激情夺宝2"] = {
			["key_name"]="激情夺宝2",
			["map_id"]="hd_jqdb",
			["activeName"]="激情夺宝",
			["class"]="ActivityMapLogic",
			["openDay"]=1,
			["runType"]="RunOnDay",
			["starttime"]="09:00:00",
			["stoptime"]="09:15:00", 
			["tip_desc"]="【激情夺宝】活动开放，击杀撒旦魔王必爆撒旦宝箱，持有宝箱5分钟即可获得宝箱奖励!", 
		},
		["乱斗之王2"] = {
			["key_name"]="乱斗之王2",
			["map_id"]="hd_ldzw",
			["activeName"]="乱斗之王",
			["class"]="ActivityMapLogic",
			["openDay"]=1,
			["runType"]="RunOnDay",
			["starttime"]="17:00:00",
			["stoptime"]="17:15:00", 
			["tip_desc"]="【乱斗之王】活动开放，生存值排名前三者可获得【乱斗之王】限时称号奖励!", 
		},
		["乱斗之王3"] = {
			["key_name"]="乱斗之王3",
			["map_id"]="hd_ldzw",
			["activeName"]="乱斗之王",
			["class"]="ActivityMapLogic",
			["openDay"]=1,
			["runType"]="RunOnDay",
			["starttime"]="23:00:00",
			["stoptime"]="23:15:00", 
			["tip_desc"]="【乱斗之王】活动开放，生存值排名前三者可获得【乱斗之王】限时称号奖励!", 
		},
		["狂暴争霸1"] = {
			["key_name"]="狂暴争霸1",
			["map_id"]="hd_kbzb",
			["activeName"]="狂暴争霸",
			["class"]="ActivityMapLogic", 
			["tip_desc"]="【狂暴争霸】已经开放，狂暴神龙已出现在地图，必定掉落火龙装备！", 
		},
		["押镖活动"] = {
			["key_name"]="押镖活动",
			["map_id"]="hd_sbyb",
			["activeName"]="普通押镖",
			["class"]="EscortAgencyNpc",
			["openDay"]=1,
			["runType"]="RunOnDay",
			["starttime"]="20:00:00",
			["stoptime"]="21:00:00", 
			["tip_desc"]="《福威镖局》已经开放，可在土城小安全区福威镖局NPC进行押镖，大量经验等你拿，活动持续1小时！", 
		},
	},
}
 return config;