---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["Name"]="军团之地",
		["boss_name"]="异界★军团长·泰拉尔",
		["pos_x"]=152,
		["pos_y"]=185,
		["need_item"]="黄金骰子",
		["need_num"]=99,
		["resistance_harm"]=20,
		["week_pass_num"]=3,
		["award_item"]="异界水晶",
		["award_item_num"]=388,
		["total_pass_num"]=99,
		["award_title"]="武道·武道通天", 
	},
	[2] = {
 		["key_name"]=2,
		["Name"]="虚空之塔",
		["boss_name"]="异界★★虚空之主·卡赞",
		["pos_x"]=31,
		["pos_y"]=113,
		["need_item"]="黄金骰子",
		["need_num"]=99,
		["resistance_harm"]=25,
		["week_pass_num"]=3,
		["award_item"]="异界水晶",
		["award_item_num"]=688,
		["total_pass_num"]=99,
		["award_title"]="成圣·肉身成圣", 
	},
	[3] = {
 		["key_name"]=3,
		["Name"]="恶魔之书",
		["boss_name"]="异界★★★恶魔使者·路西法",
		["pos_x"]=90,
		["pos_y"]=113,
		["need_item"]="恶魔挑战卷",
		["need_num"]=99,
		["resistance_harm"]=30,
		["week_pass_num"]=3,
		["award_item"]="异界水晶",
		["award_item_num"]=988,
		["total_pass_num"]=199,
		["award_title"]="破虚·化凡为仙", 
	},
	[4] = {
 		["key_name"]=4,
		["Name"]="迷雾之森",
		["boss_name"]="异界★★★★迷雾主宰·撒旦",
		["pos_x"]=152,
		["pos_y"]=185,
		["need_item"]="恶魔挑战卷",
		["need_num"]=99,
		["resistance_harm"]=40,
		["week_pass_num"]=3,
		["award_item"]="异界魂石",
		["award_item_num"]=188,
		["total_pass_num"]=299,
		["award_title"]="碎界·寰宇称帝", 
	},
	[5] = {
 		["key_name"]=5,
		["Name"]="天空遗迹",
		["boss_name"]="异界★★★★★天空之神·宙斯",
		["pos_x"]=152,
		["pos_y"]=113,
		["need_item"]="恶魔挑战卷",
		["need_num"]=99,
		["resistance_harm"]=50,
		["week_pass_num"]=3,
		["award_item"]="异界魂石",
		["award_item_num"]=288,
		["total_pass_num"]=399,
		["award_title"]="凌霄·仙帝之尊", 
	},  
}
 return config;