---alg¹¤×÷Ì¨
---xls×ªlua table
---±¾¹¤¾ßÃâ·Ñ ½»Á÷QQÈº:436063587
local config = {
 
	["sm7"] = {
 		["key_name"]="sm7",
		["type"]="Ê¯Ä¹",
		["index"]=1,
		["number"]=20, 
	},
	["sm8"] = {
 		["key_name"]="sm8",
		["type"]="Ê¯Ä¹",
		["index"]=1,
		["number"]=20, 
	},
	["sm9"] = {
 		["key_name"]="sm9",
		["type"]="Ê¯Ä¹",
		["index"]=1,
		["number"]=20, 
	},
	["sm7_jx"] = {
 		["key_name"]="sm7_jx",
		["type"]="Ê¯Ä¹",
		["index"]=1,
		["number"]=20, 
	},
	["sm8_jx"] = {
 		["key_name"]="sm8_jx",
		["type"]="Ê¯Ä¹",
		["index"]=1,
		["number"]=20, 
	},
	["sm9_jx"] = {
 		["key_name"]="sm9_jx",
		["type"]="Ê¯Ä¹",
		["index"]=1,
		["number"]=20, 
	},
	["nmdt1"] = {
 		["key_name"]="nmdt1",
		["type"]="Å£Ä§",
		["index"]=2,
		["number"]=20, 
	},
	["nmdt2"] = {
 		["key_name"]="nmdt2",
		["type"]="Å£Ä§",
		["index"]=2,
		["number"]=20, 
	},
	["nmdt3"] = {
 		["key_name"]="nmdt3",
		["type"]="Å£Ä§",
		["index"]=2,
		["number"]=20, 
	},
	["nmdt1_jx"] = {
 		["key_name"]="nmdt1_jx",
		["type"]="Å£Ä§",
		["index"]=2,
		["number"]=20, 
	},
	["nmdt2_jx"] = {
 		["key_name"]="nmdt2_jx",
		["type"]="Å£Ä§",
		["index"]=2,
		["number"]=20, 
	},
	["nmdt3_jx"] = {
 		["key_name"]="nmdt3_jx",
		["type"]="Å£Ä§",
		["index"]=2,
		["number"]=20, 
	},
	["zmqc1"] = {
 		["key_name"]="zmqc1",
		["type"]="×æÂê",
		["index"]=3,
		["number"]=20, 
	},
	["zmqc2"] = {
 		["key_name"]="zmqc2",
		["type"]="×æÂê",
		["index"]=3,
		["number"]=20, 
	},
	["zmqc3"] = {
 		["key_name"]="zmqc3",
		["type"]="×æÂê",
		["index"]=3,
		["number"]=20, 
	},
	["zmqc1_jx"] = {
 		["key_name"]="zmqc1_jx",
		["type"]="×æÂê",
		["index"]=3,
		["number"]=20, 
	},
	["zmqc2_jx"] = {
 		["key_name"]="zmqc2_jx",
		["type"]="×æÂê",
		["index"]=3,
		["number"]=20, 
	},
	["zmqc3_jx"] = {
 		["key_name"]="zmqc3_jx",
		["type"]="×æÂê",
		["index"]=3,
		["number"]=20, 
	},
	["wzjd1"] = {
 		["key_name"]="wzjd1",
		["type"]="ÍõÕß",
		["index"]=4,
		["number"]=50, 
	},
	["wzjd2"] = {
 		["key_name"]="wzjd2",
		["type"]="ÍõÕß",
		["index"]=4,
		["number"]=50, 
	},
	["wzjd1_jx"] = {
 		["key_name"]="wzjd1_jx",
		["type"]="ÍõÕß",
		["index"]=4,
		["number"]=50, 
	},
	["wzjd2_jx"] = {
 		["key_name"]="wzjd2_jx",
		["type"]="ÍõÕß",
		["index"]=4,
		["number"]=50, 
	},
	["fmdd1"] = {
 		["key_name"]="fmdd1",
		["type"]="·âÄ§",
		["index"]=5,
		["number"]=50, 
	},
	["fmdd2"] = {
 		["key_name"]="fmdd2",
		["type"]="·âÄ§",
		["index"]=5,
		["number"]=50, 
	},
	["fmdd1_jx"] = {
 		["key_name"]="fmdd1_jx",
		["type"]="·âÄ§",
		["index"]=5,
		["number"]=50, 
	},
	["fmdd2_jx"] = {
 		["key_name"]="fmdd2_jx",
		["type"]="·âÄ§",
		["index"]=5,
		["number"]=50, 
	},
	["mysd1"] = {
 		["key_name"]="mysd1",
		["type"]="ÂêÑÅ",
		["index"]=6,
		["number"]=50, 
	},
	["mysd2"] = {
 		["key_name"]="mysd2",
		["type"]="ÂêÑÅ",
		["index"]=6,
		["number"]=50, 
	},
	["mysd1_jx"] = {
 		["key_name"]="mysd1_jx",
		["type"]="ÂêÑÅ",
		["index"]=6,
		["number"]=50, 
	},
	["mysd2_jx"] = {
 		["key_name"]="mysd2_jx",
		["type"]="ÂêÑÅ",
		["index"]=6,
		["number"]=50, 
	},
	["scbg1"] = {
 		["key_name"]="scbg1",
		["type"]="É³±¦",
		["index"]=7,
		["number"]=100, 
	},
	["scbg2"] = {
 		["key_name"]="scbg2",
		["type"]="É³±¦",
		["index"]=7,
		["number"]=100, 
	},
	["scbg1_jx"] = {
 		["key_name"]="scbg1_jx",
		["type"]="É³±¦",
		["index"]=7,
		["number"]=100, 
	},
	["scbg2_jx"] = {
 		["key_name"]="scbg2_jx",
		["type"]="É³±¦",
		["index"]=7,
		["number"]=100, 
	},
	["mlld1"] = {
 		["key_name"]="mlld1",
		["type"]="Ä§Áú",
		["index"]=8,
		["number"]=100, 
	},
	["mlld2"] = {
 		["key_name"]="mlld2",
		["type"]="Ä§Áú",
		["index"]=8,
		["number"]=100, 
	},
	["mlld1_jx"] = {
 		["key_name"]="mlld1_jx",
		["type"]="Ä§Áú",
		["index"]=8,
		["number"]=100, 
	},
	["mlld2_jx"] = {
 		["key_name"]="mlld2_jx",
		["type"]="Ä§Áú",
		["index"]=8,
		["number"]=100, 
	},
	["hlcx1"] = {
 		["key_name"]="hlcx1",
		["type"]="»ğÁú",
		["index"]=9,
		["number"]=100, 
	},
	["hlcx2"] = {
 		["key_name"]="hlcx2",
		["type"]="»ğÁú",
		["index"]=9,
		["number"]=100, 
	},
	["hlcx1_jx"] = {
 		["key_name"]="hlcx1_jx",
		["type"]="»ğÁú",
		["index"]=9,
		["number"]=100, 
	},
	["hlcx2_jx"] = {
 		["key_name"]="hlcx2_jx",
		["type"]="»ğÁú",
		["index"]=9,
		["number"]=100, 
	},
	["dyzm1"] = {
 		["key_name"]="dyzm1",
		["type"]="µØÓüÖ®ÃÅ",
		["index"]=10,
		["number"]=200, 
	},
	["dyzm2"] = {
 		["key_name"]="dyzm2",
		["type"]="µØÓüÖ®ÃÅ",
		["index"]=10,
		["number"]=200, 
	},
	["dyzm3"] = {
 		["key_name"]="dyzm3",
		["type"]="µØÓüÖ®ÃÅ",
		["index"]=10,
		["number"]=200, 
	},
	["dyzm1_jx"] = {
 		["key_name"]="dyzm1_jx",
		["type"]="µØÓüÖ®ÃÅ",
		["index"]=10,
		["number"]=200, 
	},
	["dyzm2_jx"] = {
 		["key_name"]="dyzm2_jx",
		["type"]="µØÓüÖ®ÃÅ",
		["index"]=10,
		["number"]=200, 
	},
	["dyzm3_jx"] = {
 		["key_name"]="dyzm3_jx",
		["type"]="µØÓüÖ®ÃÅ",
		["index"]=10,
		["number"]=200, 
	},
	["wlgm1"] = {
 		["key_name"]="wlgm1",
		["type"]="ÍöÁé¹ÅÄ¹",
		["index"]=11,
		["number"]=200, 
	},
	["wlgm2"] = {
 		["key_name"]="wlgm2",
		["type"]="ÍöÁé¹ÅÄ¹",
		["index"]=11,
		["number"]=200, 
	},
	["wlgm3"] = {
 		["key_name"]="wlgm3",
		["type"]="ÍöÁé¹ÅÄ¹",
		["index"]=11,
		["number"]=200, 
	},
	["wlgm1_jx"] = {
 		["key_name"]="wlgm1_jx",
		["type"]="ÍöÁé¹ÅÄ¹",
		["index"]=11,
		["number"]=200, 
	},
	["wlgm2_jx"] = {
 		["key_name"]="wlgm2_jx",
		["type"]="ÍöÁé¹ÅÄ¹",
		["index"]=11,
		["number"]=200, 
	},
	["wlgm3_jx"] = {
 		["key_name"]="wlgm3_jx",
		["type"]="ÍöÁé¹ÅÄ¹",
		["index"]=11,
		["number"]=200, 
	},
	["yghl1"] = {
 		["key_name"]="yghl1",
		["type"]="Ô¶¹Å»ÊÁê",
		["index"]=12,
		["number"]=200, 
	},
	["yghl2"] = {
 		["key_name"]="yghl2",
		["type"]="Ô¶¹Å»ÊÁê",
		["index"]=12,
		["number"]=200, 
	},
	["yghl3"] = {
 		["key_name"]="yghl3",
		["type"]="Ô¶¹Å»ÊÁê",
		["index"]=12,
		["number"]=200, 
	},
	["yghl1_jx"] = {
 		["key_name"]="yghl1_jx",
		["type"]="Ô¶¹Å»ÊÁê",
		["index"]=12,
		["number"]=200, 
	},
	["yghl2_jx"] = {
 		["key_name"]="yghl2_jx",
		["type"]="Ô¶¹Å»ÊÁê",
		["index"]=12,
		["number"]=200, 
	},
	["yghl3_jx"] = {
 		["key_name"]="yghl3_jx",
		["type"]="Ô¶¹Å»ÊÁê",
		["index"]=12,
		["number"]=200, 
	},
	["bscb1"] = {
 		["key_name"]="bscb1",
		["type"]="±ùËª³Ç±¤",
		["index"]=13,
		["number"]=500, 
	},
	["bscb2"] = {
 		["key_name"]="bscb2",
		["type"]="±ùËª³Ç±¤",
		["index"]=13,
		["number"]=500, 
	},
	["bscb3"] = {
 		["key_name"]="bscb3",
		["type"]="±ùËª³Ç±¤",
		["index"]=13,
		["number"]=500, 
	},
	["bscb1_jx"] = {
 		["key_name"]="bscb1_jx",
		["type"]="±ùËª³Ç±¤",
		["index"]=13,
		["number"]=500, 
	},
	["bscb2_jx"] = {
 		["key_name"]="bscb2_jx",
		["type"]="±ùËª³Ç±¤",
		["index"]=13,
		["number"]=500, 
	},
	["bscb3_jx"] = {
 		["key_name"]="bscb3_jx",
		["type"]="±ùËª³Ç±¤",
		["index"]=13,
		["number"]=500, 
	},
	["mryj1"] = {
 		["key_name"]="mryj1",
		["type"]="Ä©ÈÕÒÅ¼£",
		["index"]=14,
		["number"]=500, 
	},
	["mryj2"] = {
 		["key_name"]="mryj2",
		["type"]="Ä©ÈÕÒÅ¼£",
		["index"]=14,
		["number"]=500, 
	},
	["mryj3"] = {
 		["key_name"]="mryj3",
		["type"]="Ä©ÈÕÒÅ¼£",
		["index"]=14,
		["number"]=500, 
	},
	["mryj1_jx"] = {
 		["key_name"]="mryj1_jx",
		["type"]="Ä©ÈÕÒÅ¼£",
		["index"]=14,
		["number"]=500, 
	},
	["mryj2_jx"] = {
 		["key_name"]="mryj2_jx",
		["type"]="Ä©ÈÕÒÅ¼£",
		["index"]=14,
		["number"]=500, 
	},
	["mryj3_jx"] = {
 		["key_name"]="mryj3_jx",
		["type"]="Ä©ÈÕÒÅ¼£",
		["index"]=14,
		["number"]=500, 
	},
	["wysl1"] = {
 		["key_name"]="wysl1",
		["type"]="Î×ÑıÉ­ÁÖ",
		["index"]=15,
		["number"]=500, 
	},
	["wysl2"] = {
 		["key_name"]="wysl2",
		["type"]="Î×ÑıÉ­ÁÖ",
		["index"]=15,
		["number"]=500, 
	},
	["wysl3"] = {
 		["key_name"]="wysl3",
		["type"]="Î×ÑıÉ­ÁÖ",
		["index"]=15,
		["number"]=500, 
	},
	["wysl1_jx"] = {
 		["key_name"]="wysl1_jx",
		["type"]="Î×ÑıÉ­ÁÖ",
		["index"]=15,
		["number"]=500, 
	},
	["wysl2_jx"] = {
 		["key_name"]="wysl2_jx",
		["type"]="Î×ÑıÉ­ÁÖ",
		["index"]=15,
		["number"]=500, 
	},
	["wysl3_jx"] = {
 		["key_name"]="wysl3_jx",
		["type"]="Î×ÑıÉ­ÁÖ",
		["index"]=15,
		["number"]=500, 
	},
	["flzz1"] = {
 		["key_name"]="flzz1",
		["type"]="·¨ÀÏÕÓÔó",
		["index"]=16,
		["number"]=500, 
	},
	["flzz2"] = {
 		["key_name"]="flzz2",
		["type"]="·¨ÀÏÕÓÔó",
		["index"]=16,
		["number"]=500, 
	},
	["flzz3"] = {
 		["key_name"]="flzz3",
		["type"]="·¨ÀÏÕÓÔó",
		["index"]=16,
		["number"]=500, 
	},
	["flzz1_jx"] = {
 		["key_name"]="flzz1_jx",
		["type"]="·¨ÀÏÕÓÔó",
		["index"]=16,
		["number"]=500, 
	},
	["flzz2_jx"] = {
 		["key_name"]="flzz2_jx",
		["type"]="·¨ÀÏÕÓÔó",
		["index"]=16,
		["number"]=500, 
	},
	["flzz3_jx"] = {
 		["key_name"]="flzz3_jx",
		["type"]="·¨ÀÏÕÓÔó",
		["index"]=16,
		["number"]=500, 
	},
	["gqsm1"] = {
 		["key_name"]="gqsm1",
		["type"]="¹íÆüÉ³Ä®",
		["index"]=17,
		["number"]=500, 
	},
	["gqsm2"] = {
 		["key_name"]="gqsm2",
		["type"]="¹íÆüÉ³Ä®",
		["index"]=17,
		["number"]=500, 
	},
	["gqsm3"] = {
 		["key_name"]="gqsm3",
		["type"]="¹íÆüÉ³Ä®",
		["index"]=17,
		["number"]=500, 
	},
	["gqsm1_jx"] = {
 		["key_name"]="gqsm1_jx",
		["type"]="¹íÆüÉ³Ä®",
		["index"]=17,
		["number"]=500, 
	},
	["gqsm2_jx"] = {
 		["key_name"]="gqsm2_jx",
		["type"]="¹íÆüÉ³Ä®",
		["index"]=17,
		["number"]=500, 
	},
	["gqsm3_jx"] = {
 		["key_name"]="gqsm3_jx",
		["type"]="¹íÆüÉ³Ä®",
		["index"]=17,
		["number"]=500, 
	},
	["mssm1"] = {
 		["key_name"]="mssm1",
		["type"]="ÃÔÊ§ÉñÃí",
		["index"]=18,
		["number"]=500, 
	},
	["mssm2"] = {
 		["key_name"]="mssm2",
		["type"]="ÃÔÊ§ÉñÃí",
		["index"]=18,
		["number"]=500, 
	},
	["mssm3"] = {
 		["key_name"]="mssm3",
		["type"]="ÃÔÊ§ÉñÃí",
		["index"]=18,
		["number"]=500, 
	},
	["mssm1_jx"] = {
 		["key_name"]="mssm1_jx",
		["type"]="ÃÔÊ§ÉñÃí",
		["index"]=18,
		["number"]=500, 
	},
	["mssm2_jx"] = {
 		["key_name"]="mssm2_jx",
		["type"]="ÃÔÊ§ÉñÃí",
		["index"]=18,
		["number"]=500, 
	},
	["mssm3_jx"] = {
 		["key_name"]="mssm3_jx",
		["type"]="ÃÔÊ§ÉñÃí",
		["index"]=18,
		["number"]=500, 
	},
	["zs_bxsy"] = {
 		["key_name"]="zs_bxsy",
		["type"]="Ê±¿ÕÁÑºÛ",
		["index"]=19,
		["number"]=1000, 
	},
	["zs_fddt1"] = {
 		["key_name"]="zs_fddt1",
		["type"]="Ê±¿ÕÁÑºÛ",
		["index"]=19,
		["number"]=1000, 
	},
	["zs_fddt2"] = {
 		["key_name"]="zs_fddt2",
		["type"]="Ê±¿ÕÁÑºÛ",
		["index"]=19,
		["number"]=1000, 
	},
	["zs_hbsd"] = {
 		["key_name"]="zs_hbsd",
		["type"]="Ê±¿ÕÁÑºÛ",
		["index"]=19,
		["number"]=1000, 
	},
	["zs_hlxg1"] = {
 		["key_name"]="zs_hlxg1",
		["type"]="Ê±¿ÕÁÑºÛ",
		["index"]=19,
		["number"]=1000, 
	},
	["zs_hlxg2"] = {
 		["key_name"]="zs_hlxg2",
		["type"]="Ê±¿ÕÁÑºÛ",
		["index"]=19,
		["number"]=1000, 
	},
	["zs_bxsy_jx"] = {
 		["key_name"]="zs_bxsy_jx",
		["type"]="Ê±¿ÕÁÑºÛ",
		["index"]=19,
		["number"]=1000, 
	},
	["zs_fddt1_jx"] = {
 		["key_name"]="zs_fddt1_jx",
		["type"]="Ê±¿ÕÁÑºÛ",
		["index"]=19,
		["number"]=1000, 
	},
	["zs_fddt2_jx"] = {
 		["key_name"]="zs_fddt2_jx",
		["type"]="Ê±¿ÕÁÑºÛ",
		["index"]=19,
		["number"]=1000, 
	},
	["zs_hbsd_jx"] = {
 		["key_name"]="zs_hbsd_jx",
		["type"]="Ê±¿ÕÁÑºÛ",
		["index"]=19,
		["number"]=1000, 
	},
	["zs_hlxg1_jx"] = {
 		["key_name"]="zs_hlxg1_jx",
		["type"]="Ê±¿ÕÁÑºÛ",
		["index"]=19,
		["number"]=1000, 
	},
	["zs_hlxg2_jx"] = {
 		["key_name"]="zs_hlxg2_jx",
		["type"]="Ê±¿ÕÁÑºÛ",
		["index"]=19,
		["number"]=1000, 
	},  
}
 return config;