local config = { 
	[1] = { 
		id = 1,
		group = 1,
		level = 1,
		ids = "107#_role",
		VarCondition = "<$LEVEL>>40&<$SFUN>(U_xuemai_red#xuemai)=null&U_xuemai_red>0",
		offset = "res/public/btn_npcfh_04.png#12#12#0|res/public/btn_npcfh_04.png#12#12#0",
	},
	[2] = { 
		id = 2,
		group = 2,
		level = 1,
		ids = "109#_miBao|107#_miBao",
		VarCondition = "<$SFUN>(U_treasure_red_num#treasure)=null&U_treasure_red_num>0",
		offset = "res/public/btn_npcfh_04.png#12#12#0|res/public/btn_npcfh_04.png#12#12#0",
	},
	[3] = { 
		id = 3,
		group = 4,
		level = 1,
		ids = "102#_benefit",
		VarCondition = "<$SFUN>(U_welfarehall_red_num#WelfareHall)=null&U_welfarehall_red_num>0",
		offset = "res/public/btn_npcfh_04.png#12#12#0|res/public/btn_npcfh_04.png#12#12#0",
	},
	[4] = { 
		id = 4,
		group = 4,
		level = 1,
		ids = "102#_activity",
		VarCondition = "<$SFUN>(U_game_active_red_num#MainTopBtn#GetGameActiveRed)=null&U_game_active_red_num>0",
		offset = "res/public/btn_npcfh_04.png#12#12#0|res/public/btn_npcfh_04.png#12#12#0",
	},
	[5] = { 
		id = 5,
		group = 4,
		level = 1,
		ids = "102#_gift",
		VarCondition = "U_firstRecharge<1",
		offset = "res/public/btn_npcfh_04.png#12#12#0|res/public/btn_npcfh_04.png#12#12#0",
	},
	[6] = { 
		id = 6,
		group = 6,
		level = 1,
		ids = "102#_privilege",
		VarCondition = "U_zstq<1|U_zstq>0&J_today_zstq<=0",
		offset = "res/public/btn_npcfh_04.png#12#12#0|res/public/btn_npcfh_04.png#12#12#0",
	},
	[7] = { 
		id = 7,
		group = 6,
		level = 1,
		ids = "201#109",
		VarCondition = "<$SFUN>(U_treasure_red_num#treasure)=null&U_treasure_red_num>0",
		offset = "res/public/btn_npcfh_04.png#12#12#0|res/public/btn_npcfh_04.png#12#12#0",
	},
	[8] = { 
		id = 8,
		group = 6,
		level = 1,
		ids = "102#_cifu",
		VarCondition = "<$SFUN>(U_game_lockmagic_red_num#lockMagic)=null&U_game_lockmagic_red_num>0",
		offset = "res/public/btn_npcfh_04.png#12#12#0|res/public/btn_npcfh_04.png#12#12#0",
	},
	[9] = { 
		id = 9,
		group = 6,
		level = 1,
		ids = "102#_server_gift",
		VarCondition = "<$SFUN>(U_server_gift_red_num#OpenServerGift)=null&U_server_gift_red_num>0",
		offset = "res/public/btn_npcfh_04.png#12#12#0|res/public/btn_npcfh_04.png#12#12#0",
	},
	[10] = { 
		id = 10,
		group = 6,
		level = 1,
		ids = "102#_everyday_recharge",
		VarCondition = "J_everyday_recharge<1",
		offset = "res/public/btn_npcfh_04.png#12#12#0|res/public/btn_npcfh_04.png#12#12#0",
	},
	[11] = { 
		id = 11,
		group = 6,
		level = 1,
		ids = "109#_compound|107#_compound",
		VarCondition = "<$COMPOUND_CHECK_LIST_RED_POINT@1>=true|<$COMPOUND_CHECK_LIST_RED_POINT@2>=true|<$COMPOUND_CHECK_LIST_RED_POINT@3>=true|<$COMPOUND_CHECK_LIST_RED_POINT@4>=true|<$COMPOUND_CHECK_LIST_RED_POINT@5>=true",
		offset = "res/public/btn_npcfh_04.png#12#12#0|res/public/btn_npcfh_04.png#12#12#0",
	},
}
return config
