---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["two_group"]=1,
		["award_money1"]="绑定元宝",
		["award_money_num1"]=20000,
		["award_money2"]="绑定金刚石",
		["award_money_num2"]=100,
		["pos1"]="战神头盔",
		["pos2"]="战神项链",
		["pos3"]="战神手镯",
		["pos4"]="战神戒指",
		["pos5"]="战神腰带",
		["pos6"]="战神圣靴", 
	},
	[2] = {
 		["key_name"]=2,
		["two_group"]=2,
		["award_money1"]="绑定元宝",
		["award_money_num1"]=20000,
		["award_money2"]="绑定金刚石",
		["award_money_num2"]=100,
		["pos1"]="圣魔头盔",
		["pos2"]="圣魔项链",
		["pos3"]="圣魔手镯",
		["pos4"]="圣魔戒指",
		["pos5"]="圣魔腰带",
		["pos6"]="圣魔法靴", 
	},
	[3] = {
 		["key_name"]=3,
		["two_group"]=3,
		["award_money1"]="绑定元宝",
		["award_money_num1"]=20000,
		["award_money2"]="绑定金刚石",
		["award_money_num2"]=100,
		["pos1"]="真魂头盔",
		["pos2"]="真魂项链",
		["pos3"]="真魂手镯",
		["pos4"]="真魂戒指",
		["pos5"]="真魂腰带",
		["pos6"]="真魂道靴", 
	},
	[4] = {
 		["key_name"]=4,
		["two_group"]=1,
		["award_money1"]="绑定元宝",
		["award_money_num1"]=20000,
		["award_money2"]="绑定金刚石",
		["award_money_num2"]=100,
		["pos1"]="火龙战盔",
		["pos2"]="火龙战链",
		["pos3"]="火龙战镯",
		["pos4"]="火龙战戒",
		["pos5"]="火龙战带",
		["pos6"]="火龙战靴", 
	},
	[5] = {
 		["key_name"]=5,
		["two_group"]=2,
		["award_money1"]="绑定元宝",
		["award_money_num1"]=20000,
		["award_money2"]="绑定金刚石",
		["award_money_num2"]=100,
		["pos1"]="火龙魔盔",
		["pos2"]="火龙魔链",
		["pos3"]="火龙魔镯",
		["pos4"]="火龙魔戒",
		["pos5"]="火龙魔带",
		["pos6"]="火龙魔靴", 
	},
	[6] = {
 		["key_name"]=6,
		["two_group"]=3,
		["award_money1"]="绑定元宝",
		["award_money_num1"]=20000,
		["award_money2"]="绑定金刚石",
		["award_money_num2"]=100,
		["pos1"]="火龙道盔",
		["pos2"]="火龙道链",
		["pos3"]="火龙道镯",
		["pos4"]="火龙道戒",
		["pos5"]="火龙道带",
		["pos6"]="火龙道靴", 
	},
	[7] = {
 		["key_name"]=7,
		["two_group"]=1,
		["award_money1"]="绑定元宝",
		["award_money_num1"]=20000,
		["award_money2"]="绑定金刚石",
		["award_money_num2"]=100,
		["pos1"]="天龙战盔",
		["pos2"]="天龙战链",
		["pos3"]="天龙战镯",
		["pos4"]="天龙战戒",
		["pos5"]="天龙战带",
		["pos6"]="天龙战靴", 
	},
	[8] = {
 		["key_name"]=8,
		["two_group"]=2,
		["award_money1"]="绑定元宝",
		["award_money_num1"]=20000,
		["award_money2"]="绑定金刚石",
		["award_money_num2"]=100,
		["pos1"]="天龙魔盔",
		["pos2"]="天龙魔链",
		["pos3"]="天龙魔镯",
		["pos4"]="天龙魔戒",
		["pos5"]="天龙魔带",
		["pos6"]="天龙魔靴", 
	},
	[9] = {
 		["key_name"]=9,
		["two_group"]=3,
		["award_money1"]="绑定元宝",
		["award_money_num1"]=20000,
		["award_money2"]="绑定金刚石",
		["award_money_num2"]=100,
		["pos1"]="天龙道盔",
		["pos2"]="天龙道链",
		["pos3"]="天龙道镯",
		["pos4"]="天龙道戒",
		["pos5"]="天龙道带",
		["pos6"]="天龙道靴", 
	},
	[10] = {
 		["key_name"]=10,
		["two_group"]=1,
		["award_money1"]="绑定元宝",
		["award_money_num1"]=20000,
		["award_money2"]="绑定金刚石",
		["award_money_num2"]=100,
		["pos1"]="神龙战盔",
		["pos2"]="神龙战链",
		["pos3"]="神龙战镯",
		["pos4"]="神龙战戒",
		["pos5"]="神龙战带",
		["pos6"]="神龙战靴", 
	},
	[11] = {
 		["key_name"]=11,
		["two_group"]=2,
		["award_money1"]="绑定元宝",
		["award_money_num1"]=20000,
		["award_money2"]="绑定金刚石",
		["award_money_num2"]=100,
		["pos1"]="神龙魔盔",
		["pos2"]="神龙魔链",
		["pos3"]="神龙魔镯",
		["pos4"]="神龙魔戒",
		["pos5"]="神龙魔带",
		["pos6"]="神龙魔靴", 
	},
	[12] = {
 		["key_name"]=12,
		["two_group"]=3,
		["award_money1"]="绑定元宝",
		["award_money_num1"]=20000,
		["award_money2"]="绑定金刚石",
		["award_money_num2"]=100,
		["pos1"]="神龙道盔",
		["pos2"]="神龙道链",
		["pos3"]="神龙道镯",
		["pos4"]="神龙道戒",
		["pos5"]="神龙道带",
		["pos6"]="神龙道靴", 
	},  
}
 return config;