---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["name"]="随机",
		["item_name"]="书页",
		["item_count"]=9,
		["accumulative"]=5,
		["accumulative_item"]="绑定灵符",
		["accumulative_item_num"]=100,
		["reward_arr"]={"聖龍装备","神龙装备","天龙装备","高级材料",},
		["mapid"]="黄金森林", 
	},
	[2] = {
 		["key_name"]=2,
		["name"]="随机",
		["item_name"]="金刚锤",
		["item_count"]=9,
		["accumulative"]=10,
		["accumulative_item"]="绑定灵符",
		["accumulative_item_num"]=200, 
	},
	[3] = {
 		["key_name"]=3,
		["name"]="随机",
		["item_name"]="五彩石",
		["item_count"]=9,
		["accumulative"]=15,
		["accumulative_item"]="绑定灵符",
		["accumulative_item_num"]=400, 
	},
	[4] = {
 		["key_name"]=4,
		["name"]="随机",
		["item_name"]="八转凭证",
		["item_count"]=1,
		["accumulative"]=20,
		["accumulative_item"]="绑定灵符",
		["accumulative_item_num"]=600, 
	},
	[5] = {
 		["key_name"]=5,
		["name"]="随机",
		["item_name"]="九转凭证",
		["item_count"]=1,
		["accumulative"]=30,
		["accumulative_item"]="绑定灵符",
		["accumulative_item_num"]=1000, 
	},
	[6] = {
 		["key_name"]=6,
		["name"]="随机",
		["item_name"]="十转凭证",
		["item_count"]=1, 
	},
	[7] = {
 		["key_name"]=7,
		["name"]="随机",
		["item_name"]="宝石碎片",
		["item_count"]=9, 
	},
	[8] = {
 		["key_name"]=8,
		["name"]="随机",
		["item_name"]="风灵宝石",
		["item_count"]=1, 
	},
	[9] = {
 		["key_name"]=9,
		["name"]="随机",
		["item_name"]="火灵宝石",
		["item_count"]=1, 
	},
	[10] = {
 		["key_name"]=10,
		["name"]="随机",
		["item_name"]="水灵宝石",
		["item_count"]=1, 
	},
	[11] = {
 		["key_name"]=11,
		["name"]="随机",
		["item_name"]="雷灵宝石",
		["item_count"]=1, 
	},
	[12] = {
 		["key_name"]=12,
		["name"]="随机",
		["item_name"]="诅咒宝石",
		["item_count"]=1, 
	},
	[13] = {
 		["key_name"]=13,
		["name"]="随机",
		["item_name"]="灵石",
		["item_count"]=1, 
	},
	[14] = {
 		["key_name"]=14,
		["name"]="随机",
		["item_name"]="玄灵石",
		["item_count"]=1, 
	},
	[15] = {
 		["key_name"]=15,
		["name"]="随机",
		["item_name"]="巨兽头颅",
		["item_count"]=1, 
	},
	[16] = {
 		["key_name"]=16,
		["name"]="随机",
		["item_name"]="魔王头颅",
		["item_count"]=1, 
	},
	[17] = {
 		["key_name"]=17,
		["name"]="随机",
		["item_name"]="泰坦之心",
		["item_count"]=1, 
	},
	[18] = {
 		["key_name"]=18,
		["name"]="随机",
		["item_name"]="巨魔之角",
		["item_count"]=1, 
	},
	[19] = {
 		["key_name"]=19,
		["name"]="随机",
		["item_name"]="大魔王之眼",
		["item_count"]=1, 
	},
	[20] = {
 		["key_name"]=20,
		["name"]="随机",
		["item_name"]="泰坦魔神之魂",
		["item_count"]=1, 
	},
	[21] = {
 		["key_name"]=21,
		["name"]="随机",
		["item_name"]="十倍秘境卷轴",
		["item_count"]=1, 
	},
	[22] = {
 		["key_name"]=22,
		["name"]="随机",
		["item_name"]="恶魔挑战卷",
		["item_count"]=1, 
	},
	[23] = {
 		["key_name"]=23,
		["name"]="随机",
		["item_name"]="龙之血",
		["item_count"]=1, 
	},
	[24] = {
 		["key_name"]=24,
		["name"]="随机",
		["item_name"]="龙之心",
		["item_count"]=1, 
	},
	[25] = {
 		["key_name"]=25,
		["name"]="随机",
		["item_name"]="神灵石",
		["item_count"]=1, 
	},
	[26] = {
 		["key_name"]=26,
		["name"]="随机",
		["item_name"]="五魂石",
		["item_count"]=1, 
	},
	[27] = {
 		["key_name"]=27,
		["name"]="四格",
		["item_name"]="绑定金刚石",
		["item_count"]=1000, 
	},
	[28] = {
 		["key_name"]=28,
		["name"]="四格",
		["item_name"]="绑定金刚石",
		["item_count"]=1000, 
	},
	[29] = {
 		["key_name"]=29,
		["name"]="四格",
		["item_name"]="绑定金刚石",
		["item_count"]=1000, 
	},
	[30] = {
 		["key_name"]=30,
		["name"]="四格",
		["item_name"]="绑定金刚石",
		["item_count"]=1000, 
	},
	[31] = {
 		["key_name"]=31,
		["name"]="中心",
		["item_name"]="声望",
		["item_count"]=1000, 
	},  
}
 return config;