---alg工作台
---xls转lua table
---时间:Fri Jul 04 15:25:17 CST 2025
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["position"]=20, 
	},
	[2] = {
 		["key_name"]=2,
		["position"]=26, 
	},
	[3] = {
 		["key_name"]=3,
		["position"]=22, 
	},
	[4] = {
 		["key_name"]=4,
		["position"]=23, 
	},
	[5] = {
 		["key_name"]=5,
		["position"]=24, 
	},
	[6] = {
 		["key_name"]=6,
		["position"]=25, 
	},
	[7] = {
 		["key_name"]=7,
		["position"]=27, 
	},
	[8] = {
 		["key_name"]=8,
		["position"]=28, 
	},
	["神秘·头盔"] = {
 		["key_name"]="神秘·头盔",
		["next"]="神秘·头盔(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["神秘·项链"] = {
 		["key_name"]="神秘·项链",
		["next"]="神秘·项链(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["神秘·手镯"] = {
 		["key_name"]="神秘·手镯",
		["next"]="神秘·手镯(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["神秘·戒指"] = {
 		["key_name"]="神秘·戒指",
		["next"]="神秘·戒指(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["神秘·腰带"] = {
 		["key_name"]="神秘·腰带",
		["next"]="神秘·腰带(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["神秘·靴子"] = {
 		["key_name"]="神秘·靴子",
		["next"]="神秘·靴子(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["神秘·头盔(SR)"] = {
 		["key_name"]="神秘·头盔(SR)",
		["next"]="神秘·头盔(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["神秘·项链(SR)"] = {
 		["key_name"]="神秘·项链(SR)",
		["next"]="神秘·项链(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["神秘·手镯(SR)"] = {
 		["key_name"]="神秘·手镯(SR)",
		["next"]="神秘·手镯(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["神秘·戒指(SR)"] = {
 		["key_name"]="神秘·戒指(SR)",
		["next"]="神秘·戒指(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["神秘·腰带(SR)"] = {
 		["key_name"]="神秘·腰带(SR)",
		["next"]="神秘·腰带(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["神秘·靴子(SR)"] = {
 		["key_name"]="神秘·靴子(SR)",
		["next"]="神秘·靴子(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["神秘·头盔(UR)"] = {
 		["key_name"]="神秘·头盔(UR)",
		["next"]="神秘·头盔(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["神秘·项链(UR)"] = {
 		["key_name"]="神秘·项链(UR)",
		["next"]="神秘·项链(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["神秘·手镯(UR)"] = {
 		["key_name"]="神秘·手镯(UR)",
		["next"]="神秘·手镯(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["神秘·戒指(UR)"] = {
 		["key_name"]="神秘·戒指(UR)",
		["next"]="神秘·戒指(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["神秘·腰带(UR)"] = {
 		["key_name"]="神秘·腰带(UR)",
		["next"]="神秘·腰带(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["神秘·靴子(UR)"] = {
 		["key_name"]="神秘·靴子(UR)",
		["next"]="神秘·靴子(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["神秘·头盔(SP)"] = {
 		["key_name"]="神秘·头盔(SP)",
		["next"]="神秘·头盔(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["神秘·项链(SP)"] = {
 		["key_name"]="神秘·项链(SP)",
		["next"]="神秘·项链(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["神秘·手镯(SP)"] = {
 		["key_name"]="神秘·手镯(SP)",
		["next"]="神秘·手镯(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["神秘·戒指(SP)"] = {
 		["key_name"]="神秘·戒指(SP)",
		["next"]="神秘·戒指(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["神秘·腰带(SP)"] = {
 		["key_name"]="神秘·腰带(SP)",
		["next"]="神秘·腰带(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["神秘·靴子(SP)"] = {
 		["key_name"]="神秘·靴子(SP)",
		["next"]="神秘·靴子(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["神秘·头盔(CP)"] = {
 		["key_name"]="神秘·头盔(CP)",
		["next"]="神秘·头盔(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["神秘·项链(CP)"] = {
 		["key_name"]="神秘·项链(CP)",
		["next"]="神秘·项链(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["神秘·手镯(CP)"] = {
 		["key_name"]="神秘·手镯(CP)",
		["next"]="神秘·手镯(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["神秘·戒指(CP)"] = {
 		["key_name"]="神秘·戒指(CP)",
		["next"]="神秘·戒指(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["神秘·腰带(CP)"] = {
 		["key_name"]="神秘·腰带(CP)",
		["next"]="神秘·腰带(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["神秘·靴子(CP)"] = {
 		["key_name"]="神秘·靴子(CP)",
		["next"]="神秘·靴子(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["神秘·头盔(GP)"] = {
 		["key_name"]="神秘·头盔(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["神秘·项链(GP)"] = {
 		["key_name"]="神秘·项链(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["神秘·手镯(GP)"] = {
 		["key_name"]="神秘·手镯(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["神秘·戒指(GP)"] = {
 		["key_name"]="神秘·戒指(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["神秘·腰带(GP)"] = {
 		["key_name"]="神秘·腰带(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["神秘·靴子(GP)"] = {
 		["key_name"]="神秘·靴子(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["虹魔·头盔"] = {
 		["key_name"]="虹魔·头盔",
		["next"]="虹魔·头盔(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["虹魔·项链"] = {
 		["key_name"]="虹魔·项链",
		["next"]="虹魔·项链(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["虹魔·手镯"] = {
 		["key_name"]="虹魔·手镯",
		["next"]="虹魔·手镯(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["虹魔·戒指"] = {
 		["key_name"]="虹魔·戒指",
		["next"]="虹魔·戒指(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["虹魔·腰带"] = {
 		["key_name"]="虹魔·腰带",
		["next"]="虹魔·腰带(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["虹魔·靴子"] = {
 		["key_name"]="虹魔·靴子",
		["next"]="虹魔·靴子(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["虹魔·头盔(SR)"] = {
 		["key_name"]="虹魔·头盔(SR)",
		["next"]="虹魔·头盔(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["虹魔·项链(SR)"] = {
 		["key_name"]="虹魔·项链(SR)",
		["next"]="虹魔·项链(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["虹魔·手镯(SR)"] = {
 		["key_name"]="虹魔·手镯(SR)",
		["next"]="虹魔·手镯(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["虹魔·戒指(SR)"] = {
 		["key_name"]="虹魔·戒指(SR)",
		["next"]="虹魔·戒指(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["虹魔·腰带(SR)"] = {
 		["key_name"]="虹魔·腰带(SR)",
		["next"]="虹魔·腰带(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["虹魔·靴子(SR)"] = {
 		["key_name"]="虹魔·靴子(SR)",
		["next"]="虹魔·靴子(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["虹魔·头盔(UR)"] = {
 		["key_name"]="虹魔·头盔(UR)",
		["next"]="虹魔·头盔(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["虹魔·项链(UR)"] = {
 		["key_name"]="虹魔·项链(UR)",
		["next"]="虹魔·项链(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["虹魔·手镯(UR)"] = {
 		["key_name"]="虹魔·手镯(UR)",
		["next"]="虹魔·手镯(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["虹魔·戒指(UR)"] = {
 		["key_name"]="虹魔·戒指(UR)",
		["next"]="虹魔·戒指(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["虹魔·腰带(UR)"] = {
 		["key_name"]="虹魔·腰带(UR)",
		["next"]="虹魔·腰带(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["虹魔·靴子(UR)"] = {
 		["key_name"]="虹魔·靴子(UR)",
		["next"]="虹魔·靴子(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["虹魔·头盔(SP)"] = {
 		["key_name"]="虹魔·头盔(SP)",
		["next"]="虹魔·头盔(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["虹魔·项链(SP)"] = {
 		["key_name"]="虹魔·项链(SP)",
		["next"]="虹魔·项链(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["虹魔·手镯(SP)"] = {
 		["key_name"]="虹魔·手镯(SP)",
		["next"]="虹魔·手镯(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["虹魔·戒指(SP)"] = {
 		["key_name"]="虹魔·戒指(SP)",
		["next"]="虹魔·戒指(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["虹魔·腰带(SP)"] = {
 		["key_name"]="虹魔·腰带(SP)",
		["next"]="虹魔·腰带(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["虹魔·靴子(SP)"] = {
 		["key_name"]="虹魔·靴子(SP)",
		["next"]="虹魔·靴子(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["虹魔·头盔(CP)"] = {
 		["key_name"]="虹魔·头盔(CP)",
		["next"]="虹魔·头盔(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["虹魔·项链(CP)"] = {
 		["key_name"]="虹魔·项链(CP)",
		["next"]="虹魔·项链(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["虹魔·手镯(CP)"] = {
 		["key_name"]="虹魔·手镯(CP)",
		["next"]="虹魔·手镯(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["虹魔·戒指(CP)"] = {
 		["key_name"]="虹魔·戒指(CP)",
		["next"]="虹魔·戒指(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["虹魔·腰带(CP)"] = {
 		["key_name"]="虹魔·腰带(CP)",
		["next"]="虹魔·腰带(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["虹魔·靴子(CP)"] = {
 		["key_name"]="虹魔·靴子(CP)",
		["next"]="虹魔·靴子(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["虹魔·头盔(GP)"] = {
 		["key_name"]="虹魔·头盔(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["虹魔·项链(GP)"] = {
 		["key_name"]="虹魔·项链(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["虹魔·手镯(GP)"] = {
 		["key_name"]="虹魔·手镯(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["虹魔·戒指(GP)"] = {
 		["key_name"]="虹魔·戒指(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["虹魔·腰带(GP)"] = {
 		["key_name"]="虹魔·腰带(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["虹魔·靴子(GP)"] = {
 		["key_name"]="虹魔·靴子(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["魔血·头盔"] = {
 		["key_name"]="魔血·头盔",
		["next"]="魔血·头盔(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["魔血·项链"] = {
 		["key_name"]="魔血·项链",
		["next"]="魔血·项链(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["魔血·手镯"] = {
 		["key_name"]="魔血·手镯",
		["next"]="魔血·手镯(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["魔血·戒指"] = {
 		["key_name"]="魔血·戒指",
		["next"]="魔血·戒指(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["魔血·腰带"] = {
 		["key_name"]="魔血·腰带",
		["next"]="魔血·腰带(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["魔血·靴子"] = {
 		["key_name"]="魔血·靴子",
		["next"]="魔血·靴子(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["魔血·头盔(SR)"] = {
 		["key_name"]="魔血·头盔(SR)",
		["next"]="魔血·头盔(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["魔血·项链(SR)"] = {
 		["key_name"]="魔血·项链(SR)",
		["next"]="魔血·项链(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["魔血·手镯(SR)"] = {
 		["key_name"]="魔血·手镯(SR)",
		["next"]="魔血·手镯(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["魔血·戒指(SR)"] = {
 		["key_name"]="魔血·戒指(SR)",
		["next"]="魔血·戒指(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["魔血·腰带(SR)"] = {
 		["key_name"]="魔血·腰带(SR)",
		["next"]="魔血·腰带(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["魔血·靴子(SR)"] = {
 		["key_name"]="魔血·靴子(SR)",
		["next"]="魔血·靴子(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["魔血·头盔(UR)"] = {
 		["key_name"]="魔血·头盔(UR)",
		["next"]="魔血·头盔(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["魔血·项链(UR)"] = {
 		["key_name"]="魔血·项链(UR)",
		["next"]="魔血·项链(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["魔血·手镯(UR)"] = {
 		["key_name"]="魔血·手镯(UR)",
		["next"]="魔血·手镯(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["魔血·戒指(UR)"] = {
 		["key_name"]="魔血·戒指(UR)",
		["next"]="魔血·戒指(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["魔血·腰带(UR)"] = {
 		["key_name"]="魔血·腰带(UR)",
		["next"]="魔血·腰带(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["魔血·靴子(UR)"] = {
 		["key_name"]="魔血·靴子(UR)",
		["next"]="魔血·靴子(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["魔血·头盔(SP)"] = {
 		["key_name"]="魔血·头盔(SP)",
		["next"]="魔血·头盔(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["魔血·项链(SP)"] = {
 		["key_name"]="魔血·项链(SP)",
		["next"]="魔血·项链(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["魔血·手镯(SP)"] = {
 		["key_name"]="魔血·手镯(SP)",
		["next"]="魔血·手镯(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["魔血·戒指(SP)"] = {
 		["key_name"]="魔血·戒指(SP)",
		["next"]="魔血·戒指(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["魔血·腰带(SP)"] = {
 		["key_name"]="魔血·腰带(SP)",
		["next"]="魔血·腰带(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["魔血·靴子(SP)"] = {
 		["key_name"]="魔血·靴子(SP)",
		["next"]="魔血·靴子(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["魔血·头盔(CP)"] = {
 		["key_name"]="魔血·头盔(CP)",
		["next"]="魔血·头盔(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["魔血·项链(CP)"] = {
 		["key_name"]="魔血·项链(CP)",
		["next"]="魔血·项链(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["魔血·手镯(CP)"] = {
 		["key_name"]="魔血·手镯(CP)",
		["next"]="魔血·手镯(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["魔血·戒指(CP)"] = {
 		["key_name"]="魔血·戒指(CP)",
		["next"]="魔血·戒指(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["魔血·腰带(CP)"] = {
 		["key_name"]="魔血·腰带(CP)",
		["next"]="魔血·腰带(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["魔血·靴子(CP)"] = {
 		["key_name"]="魔血·靴子(CP)",
		["next"]="魔血·靴子(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["魔血·头盔(GP)"] = {
 		["key_name"]="魔血·头盔(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["魔血·项链(GP)"] = {
 		["key_name"]="魔血·项链(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["魔血·手镯(GP)"] = {
 		["key_name"]="魔血·手镯(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["魔血·戒指(GP)"] = {
 		["key_name"]="魔血·戒指(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["魔血·腰带(GP)"] = {
 		["key_name"]="魔血·腰带(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["魔血·靴子(GP)"] = {
 		["key_name"]="魔血·靴子(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["祈祷·头盔"] = {
 		["key_name"]="祈祷·头盔",
		["next"]="祈祷·头盔(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["祈祷·项链"] = {
 		["key_name"]="祈祷·项链",
		["next"]="祈祷·项链(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["祈祷·手镯"] = {
 		["key_name"]="祈祷·手镯",
		["next"]="祈祷·手镯(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["祈祷·戒指"] = {
 		["key_name"]="祈祷·戒指",
		["next"]="祈祷·戒指(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["祈祷·腰带"] = {
 		["key_name"]="祈祷·腰带",
		["next"]="祈祷·腰带(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["祈祷·靴子"] = {
 		["key_name"]="祈祷·靴子",
		["next"]="祈祷·靴子(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["祈祷·头盔(SR)"] = {
 		["key_name"]="祈祷·头盔(SR)",
		["next"]="祈祷·头盔(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["祈祷·项链(SR)"] = {
 		["key_name"]="祈祷·项链(SR)",
		["next"]="祈祷·项链(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["祈祷·手镯(SR)"] = {
 		["key_name"]="祈祷·手镯(SR)",
		["next"]="祈祷·手镯(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["祈祷·戒指(SR)"] = {
 		["key_name"]="祈祷·戒指(SR)",
		["next"]="祈祷·戒指(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["祈祷·腰带(SR)"] = {
 		["key_name"]="祈祷·腰带(SR)",
		["next"]="祈祷·腰带(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["祈祷·靴子(SR)"] = {
 		["key_name"]="祈祷·靴子(SR)",
		["next"]="祈祷·靴子(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["祈祷·头盔(UR)"] = {
 		["key_name"]="祈祷·头盔(UR)",
		["next"]="祈祷·头盔(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["祈祷·项链(UR)"] = {
 		["key_name"]="祈祷·项链(UR)",
		["next"]="祈祷·项链(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["祈祷·手镯(UR)"] = {
 		["key_name"]="祈祷·手镯(UR)",
		["next"]="祈祷·手镯(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["祈祷·戒指(UR)"] = {
 		["key_name"]="祈祷·戒指(UR)",
		["next"]="祈祷·戒指(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["祈祷·腰带(UR)"] = {
 		["key_name"]="祈祷·腰带(UR)",
		["next"]="祈祷·腰带(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["祈祷·靴子(UR)"] = {
 		["key_name"]="祈祷·靴子(UR)",
		["next"]="祈祷·靴子(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["祈祷·头盔(SP)"] = {
 		["key_name"]="祈祷·头盔(SP)",
		["next"]="祈祷·头盔(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["祈祷·项链(SP)"] = {
 		["key_name"]="祈祷·项链(SP)",
		["next"]="祈祷·项链(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["祈祷·手镯(SP)"] = {
 		["key_name"]="祈祷·手镯(SP)",
		["next"]="祈祷·手镯(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["祈祷·戒指(SP)"] = {
 		["key_name"]="祈祷·戒指(SP)",
		["next"]="祈祷·戒指(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["祈祷·腰带(SP)"] = {
 		["key_name"]="祈祷·腰带(SP)",
		["next"]="祈祷·腰带(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["祈祷·靴子(SP)"] = {
 		["key_name"]="祈祷·靴子(SP)",
		["next"]="祈祷·靴子(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["祈祷·头盔(CP)"] = {
 		["key_name"]="祈祷·头盔(CP)",
		["next"]="祈祷·头盔(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["祈祷·项链(CP)"] = {
 		["key_name"]="祈祷·项链(CP)",
		["next"]="祈祷·项链(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["祈祷·手镯(CP)"] = {
 		["key_name"]="祈祷·手镯(CP)",
		["next"]="祈祷·手镯(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["祈祷·戒指(CP)"] = {
 		["key_name"]="祈祷·戒指(CP)",
		["next"]="祈祷·戒指(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["祈祷·腰带(CP)"] = {
 		["key_name"]="祈祷·腰带(CP)",
		["next"]="祈祷·腰带(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["祈祷·靴子(CP)"] = {
 		["key_name"]="祈祷·靴子(CP)",
		["next"]="祈祷·靴子(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["祈祷·头盔(GP)"] = {
 		["key_name"]="祈祷·头盔(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["祈祷·项链(GP)"] = {
 		["key_name"]="祈祷·项链(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["祈祷·手镯(GP)"] = {
 		["key_name"]="祈祷·手镯(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["祈祷·戒指(GP)"] = {
 		["key_name"]="祈祷·戒指(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["祈祷·腰带(GP)"] = {
 		["key_name"]="祈祷·腰带(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["祈祷·靴子(GP)"] = {
 		["key_name"]="祈祷·靴子(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["狂风·头盔"] = {
 		["key_name"]="狂风·头盔",
		["next"]="狂风·头盔(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["狂风·项链"] = {
 		["key_name"]="狂风·项链",
		["next"]="狂风·项链(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["狂风·手镯"] = {
 		["key_name"]="狂风·手镯",
		["next"]="狂风·手镯(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["狂风·戒指"] = {
 		["key_name"]="狂风·戒指",
		["next"]="狂风·戒指(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["狂风·腰带"] = {
 		["key_name"]="狂风·腰带",
		["next"]="狂风·腰带(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["狂风·靴子"] = {
 		["key_name"]="狂风·靴子",
		["next"]="狂风·靴子(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["狂风·头盔(SR)"] = {
 		["key_name"]="狂风·头盔(SR)",
		["next"]="狂风·头盔(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["狂风·项链(SR)"] = {
 		["key_name"]="狂风·项链(SR)",
		["next"]="狂风·项链(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["狂风·手镯(SR)"] = {
 		["key_name"]="狂风·手镯(SR)",
		["next"]="狂风·手镯(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["狂风·戒指(SR)"] = {
 		["key_name"]="狂风·戒指(SR)",
		["next"]="狂风·戒指(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["狂风·腰带(SR)"] = {
 		["key_name"]="狂风·腰带(SR)",
		["next"]="狂风·腰带(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["狂风·靴子(SR)"] = {
 		["key_name"]="狂风·靴子(SR)",
		["next"]="狂风·靴子(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["狂风·头盔(UR)"] = {
 		["key_name"]="狂风·头盔(UR)",
		["next"]="狂风·头盔(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["狂风·项链(UR)"] = {
 		["key_name"]="狂风·项链(UR)",
		["next"]="狂风·项链(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["狂风·手镯(UR)"] = {
 		["key_name"]="狂风·手镯(UR)",
		["next"]="狂风·手镯(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["狂风·戒指(UR)"] = {
 		["key_name"]="狂风·戒指(UR)",
		["next"]="狂风·戒指(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["狂风·腰带(UR)"] = {
 		["key_name"]="狂风·腰带(UR)",
		["next"]="狂风·腰带(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["狂风·靴子(UR)"] = {
 		["key_name"]="狂风·靴子(UR)",
		["next"]="狂风·靴子(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["狂风·头盔(SP)"] = {
 		["key_name"]="狂风·头盔(SP)",
		["next"]="狂风·头盔(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["狂风·项链(SP)"] = {
 		["key_name"]="狂风·项链(SP)",
		["next"]="狂风·项链(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["狂风·手镯(SP)"] = {
 		["key_name"]="狂风·手镯(SP)",
		["next"]="狂风·手镯(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["狂风·戒指(SP)"] = {
 		["key_name"]="狂风·戒指(SP)",
		["next"]="狂风·戒指(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["狂风·腰带(SP)"] = {
 		["key_name"]="狂风·腰带(SP)",
		["next"]="狂风·腰带(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["狂风·靴子(SP)"] = {
 		["key_name"]="狂风·靴子(SP)",
		["next"]="狂风·靴子(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["狂风·头盔(CP)"] = {
 		["key_name"]="狂风·头盔(CP)",
		["next"]="狂风·头盔(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["狂风·项链(CP)"] = {
 		["key_name"]="狂风·项链(CP)",
		["next"]="狂风·项链(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["狂风·手镯(CP)"] = {
 		["key_name"]="狂风·手镯(CP)",
		["next"]="狂风·手镯(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["狂风·戒指(CP)"] = {
 		["key_name"]="狂风·戒指(CP)",
		["next"]="狂风·戒指(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["狂风·腰带(CP)"] = {
 		["key_name"]="狂风·腰带(CP)",
		["next"]="狂风·腰带(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["狂风·靴子(CP)"] = {
 		["key_name"]="狂风·靴子(CP)",
		["next"]="狂风·靴子(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["狂风·头盔(GP)"] = {
 		["key_name"]="狂风·头盔(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["狂风·项链(GP)"] = {
 		["key_name"]="狂风·项链(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["狂风·手镯(GP)"] = {
 		["key_name"]="狂风·手镯(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["狂风·戒指(GP)"] = {
 		["key_name"]="狂风·戒指(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["狂风·腰带(GP)"] = {
 		["key_name"]="狂风·腰带(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["狂风·靴子(GP)"] = {
 		["key_name"]="狂风·靴子(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["记忆·头盔"] = {
 		["key_name"]="记忆·头盔",
		["next"]="记忆·头盔(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["记忆·项链"] = {
 		["key_name"]="记忆·项链",
		["next"]="记忆·项链(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["记忆·手镯"] = {
 		["key_name"]="记忆·手镯",
		["next"]="记忆·手镯(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["记忆·戒指"] = {
 		["key_name"]="记忆·戒指",
		["next"]="记忆·戒指(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["记忆·腰带"] = {
 		["key_name"]="记忆·腰带",
		["next"]="记忆·腰带(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["记忆·靴子"] = {
 		["key_name"]="记忆·靴子",
		["next"]="记忆·靴子(SR)",
		["color_arr"]={255,250,},
		["needMaterials_map"]={["灵石"]=10,},
		["needCurrency_map"]={["元宝"]=20000,}, 
	},
	["记忆·头盔(SR)"] = {
 		["key_name"]="记忆·头盔(SR)",
		["next"]="记忆·头盔(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["记忆·项链(SR)"] = {
 		["key_name"]="记忆·项链(SR)",
		["next"]="记忆·项链(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["记忆·手镯(SR)"] = {
 		["key_name"]="记忆·手镯(SR)",
		["next"]="记忆·手镯(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["记忆·戒指(SR)"] = {
 		["key_name"]="记忆·戒指(SR)",
		["next"]="记忆·戒指(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["记忆·腰带(SR)"] = {
 		["key_name"]="记忆·腰带(SR)",
		["next"]="记忆·腰带(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["记忆·靴子(SR)"] = {
 		["key_name"]="记忆·靴子(SR)",
		["next"]="记忆·靴子(UR)",
		["color_arr"]={250,252,},
		["needMaterials_map"]={["灵石"]=50,},
		["needCurrency_map"]={["元宝"]=50000,}, 
	},
	["记忆·头盔(UR)"] = {
 		["key_name"]="记忆·头盔(UR)",
		["next"]="记忆·头盔(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["记忆·项链(UR)"] = {
 		["key_name"]="记忆·项链(UR)",
		["next"]="记忆·项链(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["记忆·手镯(UR)"] = {
 		["key_name"]="记忆·手镯(UR)",
		["next"]="记忆·手镯(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["记忆·戒指(UR)"] = {
 		["key_name"]="记忆·戒指(UR)",
		["next"]="记忆·戒指(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["记忆·腰带(UR)"] = {
 		["key_name"]="记忆·腰带(UR)",
		["next"]="记忆·腰带(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["记忆·靴子(UR)"] = {
 		["key_name"]="记忆·靴子(UR)",
		["next"]="记忆·靴子(CP)",
		["color_arr"]={252,253,},
		["needMaterials_map"]={["玄灵石"]=10,},
		["needCurrency_map"]={["金刚石"]=10000,}, 
	},
	["记忆·头盔(SP)"] = {
 		["key_name"]="记忆·头盔(SP)",
		["next"]="记忆·头盔(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["记忆·项链(SP)"] = {
 		["key_name"]="记忆·项链(SP)",
		["next"]="记忆·项链(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["记忆·手镯(SP)"] = {
 		["key_name"]="记忆·手镯(SP)",
		["next"]="记忆·手镯(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["记忆·戒指(SP)"] = {
 		["key_name"]="记忆·戒指(SP)",
		["next"]="记忆·戒指(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["记忆·腰带(SP)"] = {
 		["key_name"]="记忆·腰带(SP)",
		["next"]="记忆·腰带(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["记忆·靴子(SP)"] = {
 		["key_name"]="记忆·靴子(SP)",
		["next"]="记忆·靴子(CP)",
		["color_arr"]={243,253,},
		["needMaterials_map"]={["玄灵石"]=50,},
		["needCurrency_map"]={["元宝"]=200000,}, 
	},
	["记忆·头盔(CP)"] = {
 		["key_name"]="记忆·头盔(CP)",
		["next"]="记忆·头盔(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["记忆·项链(CP)"] = {
 		["key_name"]="记忆·项链(CP)",
		["next"]="记忆·项链(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["记忆·手镯(CP)"] = {
 		["key_name"]="记忆·手镯(CP)",
		["next"]="记忆·手镯(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["记忆·戒指(CP)"] = {
 		["key_name"]="记忆·戒指(CP)",
		["next"]="记忆·戒指(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["记忆·腰带(CP)"] = {
 		["key_name"]="记忆·腰带(CP)",
		["next"]="记忆·腰带(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["记忆·靴子(CP)"] = {
 		["key_name"]="记忆·靴子(CP)",
		["next"]="记忆·靴子(GP)",
		["color_arr"]={253,249,},
		["needMaterials_map"]={["神灵石"]=10,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["记忆·头盔(GP)"] = {
 		["key_name"]="记忆·头盔(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["记忆·项链(GP)"] = {
 		["key_name"]="记忆·项链(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["记忆·手镯(GP)"] = {
 		["key_name"]="记忆·手镯(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["记忆·戒指(GP)"] = {
 		["key_name"]="记忆·戒指(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["记忆·腰带(GP)"] = {
 		["key_name"]="记忆·腰带(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},
	["记忆·靴子(GP)"] = {
 		["key_name"]="记忆·靴子(GP)",
		["color_arr"]={249,249,},
		["needMaterials_map"]={["神灵石"]=50,},
		["needCurrency_map"]={["灵符"]=500,}, 
	},  
}
 return config;