---alg工作台
---xls转lua table
---时间:Tue Jul 08 09:51:58 CST 2025
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["num"]=0,
		["btnName"]="赤金头颅",
		["needitem1"]="头颅根骨",
		["itemnum1"]=9,
		["needitem2"]="元宝",
		["itemnum2"]=1000000,
		["success"]=20,
		["next"]="魔炎", 
	},
	[2] = {
 		["key_name"]=2,
		["num"]=0,
		["btnName"]="赤金身躯",
		["needitem1"]="身躯根骨",
		["itemnum1"]=9,
		["needitem2"]="元宝",
		["itemnum2"]=1000000,
		["success"]=20,
		["next"]="魔炎", 
	},
	[3] = {
 		["key_name"]=3,
		["num"]=0,
		["btnName"]="赤金左臂",
		["needitem1"]="左臂根骨",
		["itemnum1"]=9,
		["needitem2"]="元宝",
		["itemnum2"]=1000000,
		["success"]=20,
		["next"]="魔炎", 
	},
	[4] = {
 		["key_name"]=4,
		["num"]=0,
		["btnName"]="赤金左手",
		["needitem1"]="左手根骨",
		["itemnum1"]=9,
		["needitem2"]="元宝",
		["itemnum2"]=1000000,
		["success"]=20,
		["next"]="魔炎", 
	},
	[5] = {
 		["key_name"]=5,
		["num"]=0,
		["btnName"]="赤金右臂",
		["needitem1"]="右臂根骨",
		["itemnum1"]=9,
		["needitem2"]="元宝",
		["itemnum2"]=1000000,
		["success"]=20,
		["next"]="魔炎", 
	},
	[6] = {
 		["key_name"]=6,
		["num"]=0,
		["btnName"]="赤金右手",
		["needitem1"]="右手根骨",
		["itemnum1"]=9,
		["needitem2"]="元宝",
		["itemnum2"]=1000000,
		["success"]=20,
		["next"]="魔炎", 
	},
	[7] = {
 		["key_name"]=7,
		["num"]=0,
		["btnName"]="赤金左腿",
		["needitem1"]="左腿根骨",
		["itemnum1"]=9,
		["needitem2"]="元宝",
		["itemnum2"]=1000000,
		["success"]=20,
		["next"]="魔炎", 
	},
	[8] = {
 		["key_name"]=8,
		["num"]=0,
		["btnName"]="赤金左脚",
		["needitem1"]="左脚根骨",
		["itemnum1"]=9,
		["needitem2"]="元宝",
		["itemnum2"]=1000000,
		["success"]=20,
		["next"]="魔炎", 
	},
	[9] = {
 		["key_name"]=9,
		["num"]=0,
		["btnName"]="赤金右腿",
		["needitem1"]="右腿根骨",
		["itemnum1"]=9,
		["needitem2"]="元宝",
		["itemnum2"]=1000000,
		["success"]=20,
		["next"]="魔炎", 
	},
	[10] = {
 		["key_name"]=10,
		["num"]=0,
		["btnName"]="赤金右脚",
		["needitem1"]="右脚根骨",
		["itemnum1"]=9,
		["needitem2"]="元宝",
		["itemnum2"]=1000000,
		["success"]=20,
		["next"]="魔炎", 
	},
	[11] = {
 		["key_name"]=11,
		["num"]=1,
		["btnName"]="魔炎头颅",
		["needitem1"]="头颅根骨",
		["itemnum1"]=18,
		["needitem2"]="元宝",
		["itemnum2"]=2000000,
		["success"]=15,
		["next"]="诅咒", 
	},
	[12] = {
 		["key_name"]=12,
		["num"]=1,
		["btnName"]="魔炎身躯",
		["needitem1"]="身躯根骨",
		["itemnum1"]=18,
		["needitem2"]="元宝",
		["itemnum2"]=2000000,
		["success"]=15,
		["next"]="诅咒", 
	},
	[13] = {
 		["key_name"]=13,
		["num"]=1,
		["btnName"]="魔炎左臂",
		["needitem1"]="左臂根骨",
		["itemnum1"]=18,
		["needitem2"]="元宝",
		["itemnum2"]=2000000,
		["success"]=15,
		["next"]="诅咒", 
	},
	[14] = {
 		["key_name"]=14,
		["num"]=1,
		["btnName"]="魔炎左手",
		["needitem1"]="左手根骨",
		["itemnum1"]=18,
		["needitem2"]="元宝",
		["itemnum2"]=2000000,
		["success"]=15,
		["next"]="诅咒", 
	},
	[15] = {
 		["key_name"]=15,
		["num"]=1,
		["btnName"]="魔炎右臂",
		["needitem1"]="右臂根骨",
		["itemnum1"]=18,
		["needitem2"]="元宝",
		["itemnum2"]=2000000,
		["success"]=15,
		["next"]="诅咒", 
	},
	[16] = {
 		["key_name"]=16,
		["num"]=1,
		["btnName"]="魔炎右手",
		["needitem1"]="右手根骨",
		["itemnum1"]=18,
		["needitem2"]="元宝",
		["itemnum2"]=2000000,
		["success"]=15,
		["next"]="诅咒", 
	},
	[17] = {
 		["key_name"]=17,
		["num"]=1,
		["btnName"]="魔炎左腿",
		["needitem1"]="左腿根骨",
		["itemnum1"]=18,
		["needitem2"]="元宝",
		["itemnum2"]=2000000,
		["success"]=15,
		["next"]="诅咒", 
	},
	[18] = {
 		["key_name"]=18,
		["num"]=1,
		["btnName"]="魔炎左脚",
		["needitem1"]="左脚根骨",
		["itemnum1"]=18,
		["needitem2"]="元宝",
		["itemnum2"]=2000000,
		["success"]=15,
		["next"]="诅咒", 
	},
	[19] = {
 		["key_name"]=19,
		["num"]=1,
		["btnName"]="魔炎右腿",
		["needitem1"]="右腿根骨",
		["itemnum1"]=18,
		["needitem2"]="元宝",
		["itemnum2"]=2000000,
		["success"]=15,
		["next"]="诅咒", 
	},
	[20] = {
 		["key_name"]=20,
		["num"]=1,
		["btnName"]="魔炎右脚",
		["needitem1"]="右脚根骨",
		["itemnum1"]=18,
		["needitem2"]="元宝",
		["itemnum2"]=2000000,
		["success"]=15,
		["next"]="诅咒", 
	},
	[21] = {
 		["key_name"]=21,
		["num"]=2,
		["btnName"]="诅咒头颅",
		["needitem1"]="头颅根骨",
		["itemnum1"]=28,
		["needitem2"]="金刚石",
		["itemnum2"]=500,
		["success"]=10,
		["next"]="天命", 
	},
	[22] = {
 		["key_name"]=22,
		["num"]=2,
		["btnName"]="诅咒身躯",
		["needitem1"]="身躯根骨",
		["itemnum1"]=28,
		["needitem2"]="金刚石",
		["itemnum2"]=500,
		["success"]=10,
		["next"]="天命", 
	},
	[23] = {
 		["key_name"]=23,
		["num"]=2,
		["btnName"]="诅咒左臂",
		["needitem1"]="左臂根骨",
		["itemnum1"]=28,
		["needitem2"]="金刚石",
		["itemnum2"]=500,
		["success"]=10,
		["next"]="天命", 
	},
	[24] = {
 		["key_name"]=24,
		["num"]=2,
		["btnName"]="诅咒左手",
		["needitem1"]="左手根骨",
		["itemnum1"]=28,
		["needitem2"]="金刚石",
		["itemnum2"]=500,
		["success"]=10,
		["next"]="天命", 
	},
	[25] = {
 		["key_name"]=25,
		["num"]=2,
		["btnName"]="诅咒右臂",
		["needitem1"]="右臂根骨",
		["itemnum1"]=28,
		["needitem2"]="金刚石",
		["itemnum2"]=500,
		["success"]=10,
		["next"]="天命", 
	},
	[26] = {
 		["key_name"]=26,
		["num"]=2,
		["btnName"]="诅咒右手",
		["needitem1"]="右手根骨",
		["itemnum1"]=28,
		["needitem2"]="金刚石",
		["itemnum2"]=500,
		["success"]=10,
		["next"]="天命", 
	},
	[27] = {
 		["key_name"]=27,
		["num"]=2,
		["btnName"]="诅咒左腿",
		["needitem1"]="左腿根骨",
		["itemnum1"]=28,
		["needitem2"]="金刚石",
		["itemnum2"]=500,
		["success"]=10,
		["next"]="天命", 
	},
	[28] = {
 		["key_name"]=28,
		["num"]=2,
		["btnName"]="诅咒左脚",
		["needitem1"]="左脚根骨",
		["itemnum1"]=28,
		["needitem2"]="金刚石",
		["itemnum2"]=500,
		["success"]=10,
		["next"]="天命", 
	},
	[29] = {
 		["key_name"]=29,
		["num"]=2,
		["btnName"]="诅咒右腿",
		["needitem1"]="右腿根骨",
		["itemnum1"]=28,
		["needitem2"]="金刚石",
		["itemnum2"]=500,
		["success"]=10,
		["next"]="天命", 
	},
	[30] = {
 		["key_name"]=30,
		["num"]=2,
		["btnName"]="诅咒右脚",
		["needitem1"]="右脚根骨",
		["itemnum1"]=28,
		["needitem2"]="金刚石",
		["itemnum2"]=500,
		["success"]=10,
		["next"]="天命", 
	},
	[31] = {
 		["key_name"]=31,
		["num"]=3,
		["btnName"]="天命头颅",
		["needitem1"]="头颅根骨",
		["itemnum1"]=38,
		["needitem2"]="金刚石",
		["itemnum2"]=1000,
		["success"]=5,
		["next"]="血脉", 
	},
	[32] = {
 		["key_name"]=32,
		["num"]=3,
		["btnName"]="天命身躯",
		["needitem1"]="身躯根骨",
		["itemnum1"]=38,
		["needitem2"]="金刚石",
		["itemnum2"]=1000,
		["success"]=5,
		["next"]="血脉", 
	},
	[33] = {
 		["key_name"]=33,
		["num"]=3,
		["btnName"]="天命左臂",
		["needitem1"]="左臂根骨",
		["itemnum1"]=38,
		["needitem2"]="金刚石",
		["itemnum2"]=1000,
		["success"]=5,
		["next"]="血脉", 
	},
	[34] = {
 		["key_name"]=34,
		["num"]=3,
		["btnName"]="天命左手",
		["needitem1"]="左手根骨",
		["itemnum1"]=38,
		["needitem2"]="金刚石",
		["itemnum2"]=1000,
		["success"]=5,
		["next"]="血脉", 
	},
	[35] = {
 		["key_name"]=35,
		["num"]=3,
		["btnName"]="天命右臂",
		["needitem1"]="右臂根骨",
		["itemnum1"]=38,
		["needitem2"]="金刚石",
		["itemnum2"]=1000,
		["success"]=5,
		["next"]="血脉", 
	},
	[36] = {
 		["key_name"]=36,
		["num"]=3,
		["btnName"]="天命右手",
		["needitem1"]="右手根骨",
		["itemnum1"]=38,
		["needitem2"]="金刚石",
		["itemnum2"]=1000,
		["success"]=5,
		["next"]="血脉", 
	},
	[37] = {
 		["key_name"]=37,
		["num"]=3,
		["btnName"]="天命左腿",
		["needitem1"]="左腿根骨",
		["itemnum1"]=38,
		["needitem2"]="金刚石",
		["itemnum2"]=1000,
		["success"]=5,
		["next"]="血脉", 
	},
	[38] = {
 		["key_name"]=38,
		["num"]=3,
		["btnName"]="天命左脚",
		["needitem1"]="左脚根骨",
		["itemnum1"]=38,
		["needitem2"]="金刚石",
		["itemnum2"]=1000,
		["success"]=5,
		["next"]="血脉", 
	},
	[39] = {
 		["key_name"]=39,
		["num"]=3,
		["btnName"]="天命右腿",
		["needitem1"]="右腿根骨",
		["itemnum1"]=38,
		["needitem2"]="金刚石",
		["itemnum2"]=1000,
		["success"]=5,
		["next"]="血脉", 
	},
	[40] = {
 		["key_name"]=40,
		["num"]=3,
		["btnName"]="天命右脚",
		["needitem1"]="右脚根骨",
		["itemnum1"]=38,
		["needitem2"]="金刚石",
		["itemnum2"]=1000,
		["success"]=5,
		["next"]="血脉", 
	},
	[41] = {
 		["key_name"]=41,
		["num"]=4,
		["btnName"]="血脉头颅",
		["needitem1"]="头颅根骨",
		["itemnum1"]=48,
		["needitem2"]="金刚石",
		["itemnum2"]=2000,
		["success"]=2,
		["next"]="無双", 
	},
	[42] = {
 		["key_name"]=42,
		["num"]=4,
		["btnName"]="血脉身躯",
		["needitem1"]="身躯根骨",
		["itemnum1"]=48,
		["needitem2"]="金刚石",
		["itemnum2"]=2000,
		["success"]=2,
		["next"]="無双", 
	},
	[43] = {
 		["key_name"]=43,
		["num"]=4,
		["btnName"]="血脉左臂",
		["needitem1"]="左臂根骨",
		["itemnum1"]=48,
		["needitem2"]="金刚石",
		["itemnum2"]=2000,
		["success"]=2,
		["next"]="無双", 
	},
	[44] = {
 		["key_name"]=44,
		["num"]=4,
		["btnName"]="血脉左手",
		["needitem1"]="左手根骨",
		["itemnum1"]=48,
		["needitem2"]="金刚石",
		["itemnum2"]=2000,
		["success"]=2,
		["next"]="無双", 
	},
	[45] = {
 		["key_name"]=45,
		["num"]=4,
		["btnName"]="血脉右臂",
		["needitem1"]="右臂根骨",
		["itemnum1"]=48,
		["needitem2"]="金刚石",
		["itemnum2"]=2000,
		["success"]=2,
		["next"]="無双", 
	},
	[46] = {
 		["key_name"]=46,
		["num"]=4,
		["btnName"]="血脉右手",
		["needitem1"]="右手根骨",
		["itemnum1"]=48,
		["needitem2"]="金刚石",
		["itemnum2"]=2000,
		["success"]=2,
		["next"]="無双", 
	},
	[47] = {
 		["key_name"]=47,
		["num"]=4,
		["btnName"]="血脉左腿",
		["needitem1"]="左腿根骨",
		["itemnum1"]=48,
		["needitem2"]="金刚石",
		["itemnum2"]=2000,
		["success"]=2,
		["next"]="無双", 
	},
	[48] = {
 		["key_name"]=48,
		["num"]=4,
		["btnName"]="血脉左脚",
		["needitem1"]="左脚根骨",
		["itemnum1"]=48,
		["needitem2"]="金刚石",
		["itemnum2"]=2000,
		["success"]=2,
		["next"]="無双", 
	},
	[49] = {
 		["key_name"]=49,
		["num"]=4,
		["btnName"]="血脉右腿",
		["needitem1"]="右腿根骨",
		["itemnum1"]=48,
		["needitem2"]="金刚石",
		["itemnum2"]=2000,
		["success"]=2,
		["next"]="無双", 
	},
	[50] = {
 		["key_name"]=50,
		["num"]=4,
		["btnName"]="血脉右脚",
		["needitem1"]="右脚根骨",
		["itemnum1"]=48,
		["needitem2"]="金刚石",
		["itemnum2"]=2000,
		["success"]=2,
		["next"]="無双", 
	},
	[51] = {
 		["key_name"]=51,
		["num"]=5,
		["btnName"]="無双头颅",
		["needitem1"]="头颅根骨",
		["itemnum1"]=58,
		["needitem2"]="金刚石",
		["itemnum2"]=5000,
		["success"]=1, 
	},
	[52] = {
 		["key_name"]=52,
		["num"]=5,
		["btnName"]="無双身躯",
		["needitem1"]="身躯根骨",
		["itemnum1"]=58,
		["needitem2"]="金刚石",
		["itemnum2"]=5000,
		["success"]=1, 
	},
	[53] = {
 		["key_name"]=53,
		["num"]=5,
		["btnName"]="無双左臂",
		["needitem1"]="左臂根骨",
		["itemnum1"]=58,
		["needitem2"]="金刚石",
		["itemnum2"]=5000,
		["success"]=1, 
	},
	[54] = {
 		["key_name"]=54,
		["num"]=5,
		["btnName"]="無双左手",
		["needitem1"]="左手根骨",
		["itemnum1"]=58,
		["needitem2"]="金刚石",
		["itemnum2"]=5000,
		["success"]=1, 
	},
	[55] = {
 		["key_name"]=55,
		["num"]=5,
		["btnName"]="無双右臂",
		["needitem1"]="右臂根骨",
		["itemnum1"]=58,
		["needitem2"]="金刚石",
		["itemnum2"]=5000,
		["success"]=1, 
	},
	[56] = {
 		["key_name"]=56,
		["num"]=5,
		["btnName"]="無双右手",
		["needitem1"]="右手根骨",
		["itemnum1"]=58,
		["needitem2"]="金刚石",
		["itemnum2"]=5000,
		["success"]=1, 
	},
	[57] = {
 		["key_name"]=57,
		["num"]=5,
		["btnName"]="無双左腿",
		["needitem1"]="左腿根骨",
		["itemnum1"]=58,
		["needitem2"]="金刚石",
		["itemnum2"]=5000,
		["success"]=1, 
	},
	[58] = {
 		["key_name"]=58,
		["num"]=5,
		["btnName"]="無双左脚",
		["needitem1"]="左脚根骨",
		["itemnum1"]=58,
		["needitem2"]="金刚石",
		["itemnum2"]=5000,
		["success"]=1, 
	},
	[59] = {
 		["key_name"]=59,
		["num"]=5,
		["btnName"]="無双右腿",
		["needitem1"]="右腿根骨",
		["itemnum1"]=58,
		["needitem2"]="金刚石",
		["itemnum2"]=5000,
		["success"]=1, 
	},
	[60] = {
 		["key_name"]=60,
		["num"]=5,
		["btnName"]="無双右脚",
		["needitem1"]="右脚根骨",
		["itemnum1"]=58,
		["needitem2"]="金刚石",
		["itemnum2"]=5000,
		["success"]=1, 
	},
	[61] = {
 		["key_name"]=61,
		["num"]=6,
		["btnName"]="头颅",
		["needitem1"]="头颅根骨",
		["itemnum1"]=0,
		["needitem2"]="金刚石",
		["itemnum2"]=0,
		["success"]=1, 
	},
	[62] = {
 		["key_name"]=62,
		["num"]=6,
		["btnName"]="身躯",
		["needitem1"]="身躯根骨",
		["itemnum1"]=0,
		["needitem2"]="金刚石",
		["itemnum2"]=0,
		["success"]=1, 
	},
	[63] = {
 		["key_name"]=63,
		["num"]=6,
		["btnName"]="左臂",
		["needitem1"]="左臂根骨",
		["itemnum1"]=0,
		["needitem2"]="金刚石",
		["itemnum2"]=0,
		["success"]=1, 
	},
	[64] = {
 		["key_name"]=64,
		["num"]=6,
		["btnName"]="左手",
		["needitem1"]="左手根骨",
		["itemnum1"]=0,
		["needitem2"]="金刚石",
		["itemnum2"]=0,
		["success"]=1, 
	},
	[65] = {
 		["key_name"]=65,
		["num"]=6,
		["btnName"]="右臂",
		["needitem1"]="右臂根骨",
		["itemnum1"]=0,
		["needitem2"]="金刚石",
		["itemnum2"]=0,
		["success"]=1, 
	},
	[66] = {
 		["key_name"]=66,
		["num"]=6,
		["btnName"]="右手",
		["needitem1"]="右手根骨",
		["itemnum1"]=0,
		["needitem2"]="金刚石",
		["itemnum2"]=0,
		["success"]=1, 
	},
	[67] = {
 		["key_name"]=67,
		["num"]=6,
		["btnName"]="左腿",
		["needitem1"]="左腿根骨",
		["itemnum1"]=0,
		["needitem2"]="金刚石",
		["itemnum2"]=0,
		["success"]=1, 
	},
	[68] = {
 		["key_name"]=68,
		["num"]=6,
		["btnName"]="左脚",
		["needitem1"]="左脚根骨",
		["itemnum1"]=0,
		["needitem2"]="金刚石",
		["itemnum2"]=0,
		["success"]=1, 
	},
	[69] = {
 		["key_name"]=69,
		["num"]=6,
		["btnName"]="右腿",
		["needitem1"]="右腿根骨",
		["itemnum1"]=0,
		["needitem2"]="金刚石",
		["itemnum2"]=0,
		["success"]=1, 
	},
	[70] = {
 		["key_name"]=70,
		["num"]=6,
		["btnName"]="右脚",
		["needitem1"]="右脚根骨",
		["itemnum1"]=0,
		["needitem2"]="金刚石",
		["itemnum2"]=0,
		["success"]=1, 
	},
	["reward"] = {
 		["key_name"]="reward",
		[1]={"赤金金身(专属装扮)"},
		[2]={"魔炎金身(专属装扮)"},
		[3]={"诅咒金身(专属装扮)"},
		[4]={"天命金身(专属装扮)"},
		[5]={"血脉金身(专属装扮)"},
		[6]={"無双金身(专属装扮)"},
	},	
}
 return config;