---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["group_type"]=1,
		["item_name"]="书页",
		["item_num"]=9,
		["weight"]=5.50,
		["last_item"]="沙之书",
		["last_item_num"]=99,
		["last_weight"]=0.05, 
	},
	[2] = {
 		["key_name"]=2,
		["group_type"]=1,
		["item_name"]="金刚锤",
		["item_num"]=9,
		["weight"]=5.50,
		["last_item"]="智慧魔石",
		["last_item_num"]=3,
		["last_weight"]=0.05, 
	},
	[3] = {
 		["key_name"]=3,
		["group_type"]=1,
		["item_name"]="五彩石",
		["item_num"]=9,
		["weight"]=5.50,
		["last_item"]="力量魔石",
		["last_item_num"]=3,
		["last_weight"]=0.05, 
	},
	[4] = {
 		["key_name"]=4,
		["group_type"]=1,
		["item_name"]="八转凭证",
		["item_num"]=1,
		["weight"]=5.50,
		["last_item"]="自然魔石",
		["last_item_num"]=3,
		["last_weight"]=0.05, 
	},
	[5] = {
 		["key_name"]=5,
		["group_type"]=1,
		["item_name"]="九转凭证",
		["item_num"]=1,
		["weight"]=5.50,
		["last_item"]="权利魔石",
		["last_item_num"]=3,
		["last_weight"]=0.05, 
	},
	[6] = {
 		["key_name"]=6,
		["group_type"]=1,
		["item_name"]="十转凭证",
		["item_num"]=1,
		["weight"]=5.50,
		["last_item"]="黑暗魔石",
		["last_item_num"]=3,
		["last_weight"]=0.05, 
	},
	[7] = {
 		["key_name"]=7,
		["group_type"]=1,
		["item_name"]="宝石碎片",
		["item_num"]=9,
		["weight"]=5.50,
		["last_weight"]=0.05, 
	},
	[8] = {
 		["key_name"]=8,
		["group_type"]=1,
		["item_name"]="风灵宝石",
		["item_num"]=1,
		["weight"]=5.50,
		["last_weight"]=0.05, 
	},
	[9] = {
 		["key_name"]=9,
		["group_type"]=1,
		["item_name"]="火灵宝石",
		["item_num"]=1,
		["weight"]=5.50,
		["last_weight"]=0.05, 
	},
	[10] = {
 		["key_name"]=10,
		["group_type"]=1,
		["item_name"]="水灵宝石",
		["item_num"]=1,
		["weight"]=5.50,
		["last_weight"]=0.05, 
	},
	[11] = {
 		["key_name"]=11,
		["group_type"]=1,
		["item_name"]="雷灵宝石",
		["item_num"]=1,
		["weight"]=5.50,
		["last_weight"]=0.05, 
	},
	[12] = {
 		["key_name"]=12,
		["group_type"]=1,
		["item_name"]="诅咒宝石",
		["item_num"]=1,
		["weight"]=5.50,
		["last_weight"]=0.05, 
	},
	[13] = {
 		["key_name"]=13,
		["group_type"]=1,
		["item_name"]="灵石",
		["item_num"]=1,
		["weight"]=5.50,
		["last_weight"]=0.05, 
	},
	[14] = {
 		["key_name"]=14,
		["group_type"]=1,
		["item_name"]="玄灵石",
		["item_num"]=1,
		["weight"]=5.50,
		["last_weight"]=0.05, 
	},
	[15] = {
 		["key_name"]=15,
		["group_type"]=1,
		["item_name"]="巨兽头颅",
		["item_num"]=1,
		["weight"]=5.50,
		["last_weight"]=0.05, 
	},
	[16] = {
 		["key_name"]=16,
		["group_type"]=1,
		["item_name"]="魔王头颅",
		["item_num"]=1,
		["weight"]=5.50,
		["last_weight"]=0.05, 
	},
	[17] = {
 		["key_name"]=17,
		["group_type"]=1,
		["item_name"]="恶魔挑战卷",
		["item_num"]=1,
		["weight"]=5.50,
		["last_weight"]=0.05, 
	},
	[18] = {
 		["key_name"]=18,
		["group_type"]=1,
		["item_name"]="黄金骰子",
		["item_num"]=1,
		["weight"]=5.50,
		["last_weight"]=0.05, 
	},
	[19] = {
 		["key_name"]=19,
		["group_type"]=2,
		["item_name"]="书页",
		["item_num"]=9,
		["weight"]=5.50, 
	},
	[20] = {
 		["key_name"]=20,
		["group_type"]=2,
		["item_name"]="金刚锤",
		["item_num"]=9,
		["weight"]=5.50, 
	},
	[21] = {
 		["key_name"]=21,
		["group_type"]=2,
		["item_name"]="五彩石",
		["item_num"]=9,
		["weight"]=5.50, 
	},
	[22] = {
 		["key_name"]=22,
		["group_type"]=2,
		["item_name"]="八转凭证",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[23] = {
 		["key_name"]=23,
		["group_type"]=2,
		["item_name"]="九转凭证",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[24] = {
 		["key_name"]=24,
		["group_type"]=2,
		["item_name"]="十转凭证",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[25] = {
 		["key_name"]=25,
		["group_type"]=2,
		["item_name"]="宝石碎片",
		["item_num"]=9,
		["weight"]=5.50, 
	},
	[26] = {
 		["key_name"]=26,
		["group_type"]=2,
		["item_name"]="风灵宝石",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[27] = {
 		["key_name"]=27,
		["group_type"]=2,
		["item_name"]="火灵宝石",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[28] = {
 		["key_name"]=28,
		["group_type"]=2,
		["item_name"]="水灵宝石",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[29] = {
 		["key_name"]=29,
		["group_type"]=2,
		["item_name"]="雷灵宝石",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[30] = {
 		["key_name"]=30,
		["group_type"]=2,
		["item_name"]="诅咒宝石",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[31] = {
 		["key_name"]=31,
		["group_type"]=2,
		["item_name"]="灵石",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[32] = {
 		["key_name"]=32,
		["group_type"]=2,
		["item_name"]="玄灵石",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[33] = {
 		["key_name"]=33,
		["group_type"]=2,
		["item_name"]="巨兽头颅",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[34] = {
 		["key_name"]=34,
		["group_type"]=2,
		["item_name"]="魔王头颅",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[35] = {
 		["key_name"]=35,
		["group_type"]=2,
		["item_name"]="恶魔挑战卷",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[36] = {
 		["key_name"]=36,
		["group_type"]=2,
		["item_name"]="黄金骰子",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[37] = {
 		["key_name"]=37,
		["group_type"]=3,
		["item_name"]="书页",
		["item_num"]=9,
		["weight"]=5.50, 
	},
	[38] = {
 		["key_name"]=38,
		["group_type"]=3,
		["item_name"]="金刚锤",
		["item_num"]=9,
		["weight"]=5.50, 
	},
	[39] = {
 		["key_name"]=39,
		["group_type"]=3,
		["item_name"]="五彩石",
		["item_num"]=9,
		["weight"]=5.50, 
	},
	[40] = {
 		["key_name"]=40,
		["group_type"]=3,
		["item_name"]="八转凭证",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[41] = {
 		["key_name"]=41,
		["group_type"]=3,
		["item_name"]="九转凭证",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[42] = {
 		["key_name"]=42,
		["group_type"]=3,
		["item_name"]="十转凭证",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[43] = {
 		["key_name"]=43,
		["group_type"]=3,
		["item_name"]="宝石碎片",
		["item_num"]=9,
		["weight"]=5.50, 
	},
	[44] = {
 		["key_name"]=44,
		["group_type"]=3,
		["item_name"]="风灵宝石",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[45] = {
 		["key_name"]=45,
		["group_type"]=3,
		["item_name"]="火灵宝石",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[46] = {
 		["key_name"]=46,
		["group_type"]=3,
		["item_name"]="水灵宝石",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[47] = {
 		["key_name"]=47,
		["group_type"]=3,
		["item_name"]="雷灵宝石",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[48] = {
 		["key_name"]=48,
		["group_type"]=3,
		["item_name"]="诅咒宝石",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[49] = {
 		["key_name"]=49,
		["group_type"]=3,
		["item_name"]="灵石",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[50] = {
 		["key_name"]=50,
		["group_type"]=3,
		["item_name"]="玄灵石",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[51] = {
 		["key_name"]=51,
		["group_type"]=3,
		["item_name"]="巨兽头颅",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[52] = {
 		["key_name"]=52,
		["group_type"]=3,
		["item_name"]="魔王头颅",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[53] = {
 		["key_name"]=53,
		["group_type"]=3,
		["item_name"]="恶魔挑战卷",
		["item_num"]=1,
		["weight"]=5.50, 
	},
	[54] = {
 		["key_name"]=54,
		["group_type"]=3,
		["item_name"]="黄金骰子",
		["item_num"]=1,
		["weight"]=5.50, 
	},  
}
 return config;