---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["talent_group"]="无双",
		["talent_name"]="魔女",
		["buff_id"]=50048,
		["maxlevel"]=1,
		["talent_type"]=1,
		["tanlebt_color"]=249,
		["weight"]=100, 
	},
	[2] = {
 		["key_name"]=2,
		["talent_group"]="无双",
		["talent_name"]="名刀",
		["buff_id"]=50049,
		["maxlevel"]=1,
		["talent_type"]=1,
		["tanlebt_color"]=249,
		["weight"]=100, 
	},
	[3] = {
 		["key_name"]=3,
		["talent_group"]="无双",
		["talent_name"]="辉月",
		["buff_id"]=50050,
		["maxlevel"]=1,
		["talent_type"]=1,
		["tanlebt_color"]=249,
		["weight"]=100, 
	},
	[4] = {
 		["key_name"]=4,
		["talent_group"]="无双",
		["talent_name"]="通灵",
		["buff_id"]=50051,
		["maxlevel"]=1,
		["talent_type"]=1,
		["tanlebt_color"]=249,
		["weight"]=100, 
	},
	[5] = {
 		["key_name"]=5,
		["talent_group"]="无双",
		["talent_name"]="无尽",
		["buff_id"]=50052,
		["maxlevel"]=1,
		["talent_type"]=1,
		["tanlebt_color"]=249,
		["weight"]=100, 
	},
	[6] = {
 		["key_name"]=6,
		["talent_group"]="无双",
		["talent_name"]="魔宗",
		["buff_id"]=50053,
		["maxlevel"]=1,
		["talent_type"]=1,
		["tanlebt_color"]=249,
		["weight"]=100, 
	},
	[7] = {
 		["key_name"]=7,
		["talent_group"]="无双",
		["talent_name"]="极夜",
		["buff_id"]=50054,
		["maxlevel"]=1,
		["talent_type"]=1,
		["tanlebt_color"]=249,
		["weight"]=100, 
	},
	[8] = {
 		["key_name"]=8,
		["talent_group"]="无双",
		["talent_name"]="风暴",
		["buff_id"]=50055,
		["maxlevel"]=1,
		["talent_type"]=1,
		["tanlebt_color"]=249,
		["weight"]=100, 
	},
	[9] = {
 		["key_name"]=9,
		["talent_group"]="无双",
		["talent_name"]="霸者",
		["buff_id"]=50056,
		["maxlevel"]=1,
		["talent_type"]=1,
		["tanlebt_color"]=249,
		["weight"]=100, 
	},
	[10] = {
 		["key_name"]=10,
		["talent_group"]="无双",
		["talent_name"]="冷静",
		["buff_id"]=50057,
		["maxlevel"]=1,
		["talent_type"]=1,
		["tanlebt_color"]=249,
		["weight"]=100, 
	},
	[11] = {
 		["key_name"]=11,
		["talent_group"]="无双",
		["talent_name"]="辟火",
		["buff_id"]=50058,
		["maxlevel"]=1,
		["talent_type"]=1,
		["tanlebt_color"]=249,
		["weight"]=100, 
	},
	[12] = {
 		["key_name"]=12,
		["talent_group"]="无双",
		["talent_name"]="迷踪",
		["buff_id"]=50059,
		["maxlevel"]=1,
		["talent_type"]=1,
		["tanlebt_color"]=249,
		["weight"]=100, 
	},
	[13] = {
 		["key_name"]=13,
		["talent_group"]="无双",
		["talent_name"]="破军",
		["buff_id"]=50068,
		["maxlevel"]=1,
		["talent_type"]=1,
		["tanlebt_color"]=249,
		["weight"]=100, 
	},
	[14] = {
 		["key_name"]=14,
		["talent_group"]="无双",
		["talent_name"]="武神",
		["buff_id"]=50075,
		["maxlevel"]=1,
		["talent_type"]=1,
		["tanlebt_color"]=249,
		["weight"]=100, 
	},
	[15] = {
 		["key_name"]=15,
		["talent_group"]="无双",
		["talent_name"]="嘲讽",
		["buff_id"]=60002,
		["maxlevel"]=1,
		["talent_type"]=1,
		["tanlebt_color"]=249,
		["weight"]=100, 
	},  
}
 return config;