lualib = {}
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhang.
--- DateTime: 2025/6/7 17:02
--- 一些公共方法
---

--- 打开npc面板
--- @param actor  string  玩家对象
--- @param formName string   客户端npc文件名
--- @param data string/integer/table 携带的参数
function lualib:ShowNpcUi(actor, formName, data)
    -- release_print("lualib:ShowNpcUi :", formName, data)
    local msgData = formName
    if type(data) == "table" then
        local dataJson = tbl2json(data)
        msgData = msgData .. "#" .. dataJson
    elseif data then
        msgData = msgData .. "#" .. data
    end
    sendluamsg(actor, SC_MSG_SHOW_VIEW, 0, 0, 0, msgData)
end

--- 关闭npc面板
--- @param actor  string  玩家对象
--- @param formName string   客户端npc文件名
function lualib:CloseNpcUi(actor, formName)
    sendluamsg(actor, SC_MSG_CLOSE_VIEW, 0, 0, 0, formName)
end

--- 刷新npc面板
--- @param actor  string  玩家对象
--- @param formName string   客户端npc文件名
--- @param data string/integer/table 携带的参数
function lualib:FlushNpcUi(actor, formName, data)
    local msgData = formName
    if type(data) == "table" then
        msgData = formName .. "#" .. tbl2json(data)
    elseif data then
        msgData = formName .. "#" .. data
    end
    sendluamsg(actor, SC_MSG_FLUSH_VIEW, 0, 0, 0, msgData)
end

--- 同步发送个人变量数据到客户端
--- @param actor  string  玩家对象
--- @param msgData  string   要发送给客户端的数据
function lualib:SendDataClient(actor, msgData)
    if type(msgData) == "table" then
        msgData = tbl2json(msgData)
    end
    sendluamsg(actor, SC_MSG_SEND_DATA, 0, 0, 0, msgData)
end

--- 打开奖励展示面板
--- @param actor  string  玩家对象
--- @param data string/integer/table 携带的参数
function lualib:ShowAwardTipUi(actor, data)
    -- release_print("lualib:ShowAwardTipUi :",  data)
    local msgData = ""
    if type(data) == "table" then
        local dataJson = tbl2json(data)
        msgData = msgData .. "#" .. dataJson
    elseif data then
        msgData = msgData .. "#" .. data
    end
    sendluamsg(actor, SC_MSG_SHOW_AWARD_TIP_VIEW, 0, 0, 0, msgData)
end


--- 服务端发送消息到客户端调用指定脚本的指定函数
--- @param actor  string  玩家对象
--- @param data string/integer/table 携带的参数
function lualib:CallFuncByClient(actor, func_name, data)
    -- release_print("lualib:CallFuncByClient :",  func_name, data)
    local msgData = func_name
    if nil ~= data then
        msgData = msgData .. "#" .. data
    end
    sendluamsg(actor, SC_MSG_CALL_CLIENT_FUNC, 0, 0, 0, msgData)
end