---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wu.
--- DateTime: 2025/6/7 14:09
--- 
local _IS_DEBUG = SL:GetMetaValue("PLATFORM_WINDOWS")

local lfs = require("lfs")
local npc_lua_files = {}
local file_list = {}        -- 第二层
function get_npc_files(path, pattern)
    for file in lfs.dir(path) do
        if file ~= "." and file ~= ".." then
            local filePath = path.."/"..file
            local attr = lfs.attributes(filePath)
            if attr.mode == "directory" and not file_list[file] then
                -- 标记子文件夹
                file_list[file] = true
            elseif attr.mode == "file" then
                -- 判断文件名是否符合搜索条件
                if string.match(file, pattern) then
                    local tab = SL:Split(filePath, "dev/")
                    local tab2 = SL:Split(file, ".")
                    local info = {
                        path = tab[2],
                        fileName = tab2[1]
                    }
                    table.insert(npc_lua_files, info)
                end
            end
        end
    end
end

function LoadAll()
    local server_id = tonumber(SL:GetMetaValue("SERVER_ID")) or 0
    _IS_DEBUG = server_id <= 1000
    SL:release_print("load all file, sever id:", server_id, _IS_DEBUG)

    -- 遍历 npc目录下所有.lua文件 
    if _IS_DEBUG then
        local currentDir = "dev/GUILayout/npc"
        get_npc_files(currentDir, ".lua")
        for k, v in pairs(file_list) do
            local p_path = currentDir.."/"..k
            get_npc_files(p_path, ".lua")
        end
        file_list = {}
    end

    -- require data
    local dataFiles = {
        "GUILayout/clientData/GameData"
    }
    for k, v in pairs(dataFiles) do
        SL:Require(v, true)
    end

    -- require define
    local defineFiles = {
        "GUILayout/define/ClientProtocolDefine",
        "GUILayout/define/ColorCodeDefine",
        "GUILayout/define/GameEventDefine",
        "GUILayout/define/ClassDefine",
    }
    for k, v in pairs(defineFiles) do
        SL:Require(v, true)
    end

    -- require common
    SL:Require("GUILayout/common/ViewMgr", true)
    SL:Require("GUILayout/common/SysConfigView", true)
    SL:Require("GUILayout/common/CommonProtocol", true)
    SL:Require("GUILayout/common/Animation", true)
    SL:Require("GUILayout/common/CommonFunc", true)
    SL:Require("GUILayout/common/LocalCfgCtrl", true)
    SL:Require("GUILayout/common/LocalCfgParser", true)
    SL:Require("GUILayout/common/GlobalFunc", true)

    -- require npc lua
    if _IS_DEBUG then
        for k, v in pairs(npc_lua_files) do
            -- SL:Print(v.path)
            local npc_ui = SL:Require(v.path, true)
            ViewMgr.addNpcScript(v.fileName, npc_ui)
        end
    else
        for k, v in pairs(ClassDefine) do
            -- SL:release_print(v)
            local npc_ui = SL:Require(v, true)
            ViewMgr.addNpcScript(npc_ui.Name, npc_ui)
        end
    end

    local iswin32 = SL:GetMetaValue('WINPLAYMODE')
    if not iswin32 then
        SL:Require("GUILayout/Mainnearbtn", true)
    end

    -- require main btn
    local mainBtnClass = {
        "GUILayout/main/SysRightBtn",
        "GUILayout/main/TopBtn",
    }
    for k, v in pairs(mainBtnClass) do
        SL:Require(v, true)
    end

    if _IS_DEBUG then
        SL:RegisterLUAEvent(LUA_EVENT_ROLE_PROPERTY_INITED, "GUIUtil", function()  --#region GMBox
            local parent = GUI:Win_FindParent(102)
            if parent then
                local gmBtn = GUI:Button_Create(parent, "btn_switch", -300, -200, "res/public/1900000652.png")
                GUI:Button_setTitleText(gmBtn, "GM操作")
                GUI:Button_setTitleFontSize(gmBtn, 15)
                GUI:addOnClickEvent(gmBtn, function()
                    GUI:Win_Open("A/GMBoxOBJ")
                end)
            end
        end)
    end

end

LoadAll()
