--颜色代码
COLORCODE = {}
COLORCODE.BLACK = 0
COLORCODE.WHITE = 255
COLORCODE.ORANGE = 243
COLORCODE.PURPLE = 241
COLORCODE.LIGHTPURPLE = 242
COLORCODE.DWHITE = 246
COLORCODE.GRAY = 247
COLORCODE.DGRAY = 248
COLORCODE.RED = 249
COLORCODE.GREEN = 250
COLORCODE.YELLOW = 251
COLORCODE.LIGHTYELLOW = 150
COLORCODE.DBLUE = 252
COLORCODE.BLUE = 168
COLORCODE.MAGENTA = 253
COLORCODE.SKYBLUE = 254
COLORCODE.BROWN = 59
COLORCODE.PINK = 31


COLOR = {}
--通用颜色
COLOR["YELLOW"] = "#FFCC00"
COLOR["PURPLE"] = "#E110CB"
COLOR["BLUE"] = "#1186EC"
COLOR["BLUE2"] = "#1186EC"
COLOR["GREEN"] = "#00FF00"
COLOR["LIGHTGRAY"] = "#A5A09A"
COLOR["GRAY"] = "#A5A09A"
COLOR["LIGHTBROWN"] = "#B8A085"
COLOR["BROWN"] = "#AE8852"
COLOR["RED"] = "#E11010"
COLOR["LIGHTGREEN"] = "#E1CFBF"
COLOR["DPURPLE"] = "#CD00CF"
COLOR["ORANGE"] = "#FF7F24"
COLOR["GOLD"] = "#FFD700"
COLOR["PINK"] = "#FFC0CB"
COLOR["WHITE"] = "#FFFAFA"
COLOR["BLACK"] = "#000000"


--特殊
COLOR["SYSMSG"] = COLOR["RED"]  --全服系统消息
COLOR["GUILDMSG"] = COLOR["ORANGE"]  --行会消息
COLOR["TEAMMSG"] = COLOR["BLUE"]  --组队消息
COLOR["MAPMSG"] = COLOR["LIGHTBROWN"]  --地图消息

COLOR["NOTENOUGH"] = COLOR["RED"] --缺少货币或者道具
COLOR["ENOUGH"] = COLOR["GREEN"] --满足货币或者道具

