---@diagnostic disable: undefined-doc-name
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mir.wu
--- DateTime: 2025/6/7 13:55
--- 一些公共协议处理
---

--- 服务器发送个人变量数据到客户端   100
--- @param msgID  number 消息ID
--- @param param1 number 参数1
--- @param param2 number 参数2
--- @param param3 number 参数3
--- @param msgData string 数据
SL:RegisterLuaNetMsg(SC_MSG_SEND_DATA, function(msgID, param1, param2, param3, msgData)
    -- SL:Print("收到服务器发送个人变量数据到客户端: ",param1, param2, param3, msgData)
    GameData.SetData(msgData)
    SL:onLUAEvent(LUA_EVENT_GAME_DATA, msgData)
end)

--- 服务器发送打开NPC面板消息   1000
--- @param msgID  number 消息ID
--- @param param1 number 参数1
--- @param param2 number 参数2
--- @param param3 number 参数3
--- @param msgData string 数据
SL:RegisterLuaNetMsg(SC_MSG_SHOW_VIEW, function(msgID, param1, param2, param3, msgData)
    -- SL:Print("收到服务器下发打开NPC面板: ",param1, param2, param3, msgData)
    -- npc面板
    local name = msgData
    local tab = {}
    if string.find(msgData, "#") then
        tab = SL:Split(msgData, "#")
        name = tab[1]
    end
    ViewMgr.open(name, unpack(tab, 2))
end)

--- 服务器发送关闭NPC面板消息   1001
--- @param msgID  number 消息ID
--- @param param1 number 参数1
--- @param param2 number 参数2
--- @param param3 number 参数3
--- @param msgData string 数据
SL:RegisterLuaNetMsg(SC_MSG_CLOSE_VIEW, function(msgID, param1, param2, param3, msgData)
    -- SL:Print("收到服务器下发关闭NPC面板: ",param1, param2, param3, msgData)
    -- npc面板
    local name = msgData
    ViewMgr.close(name)
end)

--- 服务器发送更新NPC面板消息   1002
--- @param msgID  number 消息ID
--- @param param1 number 参数1
--- @param param2 number 参数2
--- @param param3 number 参数3
--- @param msgData string 数据
SL:RegisterLuaNetMsg(SC_MSG_FLUSH_VIEW, function(msgID, param1, param2, param3, msgData)
    -- SL:Print("收到服务器下发刷新NPC面板: ",param1, param2, param3, msgData)
    -- npc面板
    local name = msgData
    local tab ={}
    if string.find(name, "#") then
        tab = SL:Split(name, "#")
        name = tab[1]
    end
    ViewMgr.flushView(name, unpack(tab,2))
end)

SL:RegisterLuaNetMsg(SC_MSG_SHOW_AWARD_TIP_VIEW, function(msgID, param1, param2, param3, msgData)
    -- SL:Print("收到服务器下发打开奖励展示面板: ",param1, param2, param3, msgData)
    -- npc面板
    local tab = {}
    if string.find(msgData, "#") then
        tab = SL:Split(msgData, "#")
    end
    if ViewMgr.IsOpen("CommonAwardView") then
        ViewMgr.flushView("CommonAwardView",unpack(tab,2))
    else
        ViewMgr.open("CommonAwardView", unpack(tab,2))
    end
end)

SL:RegisterLuaNetMsg(SC_MSG_CALL_CLIENT_FUNC, function(msgID, param1, param2, param3, msgData)
    -- SL:Print("收到服务器下发调用客户端指定函数: ",param1, param2, param3, msgData)
    local tab = {}
    if string.find(msgData, "#") then
        tab = SL:Split(msgData, "#")
    else
        tab = {msgData}
    end
    local func = GlobalFunc[tab[1]]
    SL:release_print(SC_MSG_CALL_CLIENT_FUNC, tab[1], func)
    if func then
        func(unpack(tab, 2))
    end
end)

--- 客户端发送数据到服务器
--- @param actor object 玩家对象
--- @param msgData string 要发送的数据
--- @param isFilter boolean 是否过滤违禁词  默认true
function SendMsgDtaSever(actor, msgData, isFilter)
    if nil == isFilter then
        isFilter = true
    end
    if type(msgData) == "table" then
        msgData = SL:JsonEncode(msgData, isFilter)
    end
    SL:SendLuaNetMsg(CS_MSG_SEND_DATA, 0, 0, 0, msgData)
end

--- 客户端点击Npc发送协议到服务器
--- @param msg_str string npc id#npc name
function SendMsgClickNpc(msg_str)
    SL:SendLuaNetMsg(CS_MSG_CLICK_NPC, 0, 0, 0, msg_str)
end

--- 客户端点击系统面板按钮发送协议到服务器
--- @param msg_str string npc id#npcClass#funcName
function SendMsgClickSysBtn(msg_str)
    SL:SendLuaNetMsg(CS_MSG_CLICK_SYS_BTN, 0, 0, 0, msg_str)
end

--- 客户端发送消息到服务器 调用指定main目录下指定lua文件的指定函数
--- @param msg_str string npc id#npcClass#funcName
function SendMsgClickMainBtn(msg_str)
    SL:SendLuaNetMsg(CS_MSG_CLICK_MAIN_BTN, 0, 0, 0, msg_str)
end

--- 客户端发送消息到服务器  调用指定npc的指定函数
--- @param npc_id integer npc配置表唯一id
--- @param className string npc类名/class类名
--- @param funName string npc函数名
--- @param msgData string/integer/table 携带的参数
function SendMsgCallFunByNpc(npc_id, className, funName, msgData)
    local msg_str = npc_id.."#"..className.."#"..funName
    if type(msgData) == "table" then
        msgData = SL:JsonEncode(msgData)
    end
    if msgData then
        msg_str = msg_str .. "#" .. msgData
    end
    SL:release_print("SendMsgCallFunByNpc: ", msg_str)
    SL:SendLuaNetMsg(CS_MSG_CALL_FUN_BY_NPC, 0, 0, 0, msg_str)
end