local config = {
    [60] = {
        group_id=111,
        desc="购买",
        group_name="交易行",
        id=60,
    },
    [61] = {
        group_id=111,
        desc="寄售",
        group_name="交易行",
        id=61,
    },
    [62] = {
        group_id=111,
        desc="货架",
        group_name="交易行",
        id=62,
    },
    [63] = {
        group_id=111,
        desc="我的",
        group_name="交易行",
        id=63,
    },
    [101] = {
        group_id=1,
        desc="装备",
        group_name="角色",
        id=101,
    },
    [102] = {
        group_id=1,
        desc="状态",
        group_name="角色",
        id=102,
    },
    [103] = {
        group_id=1,
        desc="属性",
        group_name="角色",
        id=103,
    },
    [104] = {
        group_id=1,
        desc="技能",
        group_name="角色",
        id=104,
    },
    [106] = {
        group_id=1,
        desc="称号",
        group_name="角色",
        id=106,
    },
    [120] = {
        group_id=1,
        desc="天赋",
        group_name="角色",
        id=120,
    },
    [300] = {
        group_id=60,
        desc="基础",
        group_name="设置",
        id=300,
    },
    [301] = {
        group_id=60,
        desc="视距",
        group_name="设置",
        id=301,
    },
    [302] = {
        group_id=60,
        desc="战斗",
        group_name="设置",
        id=302,
    },
    [303] = {
        group_id=60,
        desc="保护",
        group_name="设置",
        id=303,
    },
    [304] = {
        group_id=60,
        desc="挂机",
        group_name="设置",
        id=304,
    },
    [305] = {
        group_id=60,
        desc="帮助",
        group_name="设置",
        id=305,
    },
    [401] = {
        group_id=4,
        desc="邮件",
        group_name="社交",
        id=401,
    },
    [402] = {
        group_id=4,
        desc="好友",
        group_name="社交",
        id=402,
    },
    [701] = {
        group_id=7,
        desc="状态",
        group_name="内功",
        id=701,
    },
    [702] = {
        group_id=7,
        desc="技能",
        group_name="内功",
        id=702,
    },
    [703] = {
        group_id=7,
        desc="经络",
        group_name="内功",
        id=703,
    },
    [704] = {
        group_id=7,
        desc="连击",
        group_name="内功",
        id=704,
    },
    [801] = {
        group_id=4,
        desc="组队",
        group_name="社交",
        id=801,
    },
    [802] = {
        group_id=4,
        desc="附近",
        group_name="社交",
        id=802,
    },
    [901] = {
        group_id=9,
        desc="热销",
        group_name="商城",
        id=901,
    },
    [902] = {
        group_id=9,
        desc="补给",
        group_name="商城",
        id=902,
    },
    [903] = {
        group_id=9,
        desc="强化",
        group_name="商城",
        id=903,
    },
    [904] = {
        group_id=9,
        desc="兑换",
        group_name="商城",
        id=904,
    },
    [905] = {
        group_id=9,
        desc="充值",
        group_name="商城",
        id=905,
    },
    [1011] = {
        group_id=1,
        desc="时装",
        group_name="角色",
        id=1011,
    },
    [1201] = {
        group_id=12,
        desc="行会",
        group_name="行会",
        id=1201,
    },
    [1202] = {
        group_id=12,
        desc="成员",
        group_name="行会",
        id=1202,
    },
    [1203] = {
        group_id=12,
        desc="列表",
        group_name="行会",
        id=1203,
    },
}
return config
