---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["gift_key"]=[[vip666]],
		["gift_award"]=[[元宝#10000|三倍经验卷#1]], 
	},
	[2] = {
 		["key_name"]=2,
		["gift_key"]=[[vip888]],
		["gift_award"]=[[元宝#10000|金刚石#100]], 
	},
	[3] = {
 		["key_name"]=3,
		["gift_key"]=[[vip999]],
		["gift_award"]=[[元宝#10000|聚灵珠#3]], 
	},
	[4] = {
 		["key_name"]=4,
		["gift_key"]=[[zshljx]],
		["gift_award"]=[[元宝#10000|秘宝礼盒#3|聚灵珠#5|书页#50]], 
	},
	[5] = {
 		["key_name"]=5,
		["gift_key"]=[[cqsylxc]],
		["gift_award"]=[[元宝#30000|三倍经验卷#3|金刚石#100|五彩石#100]], 
	},
	[6] = {
 		["key_name"]=6,
		["gift_key"]=[[cqsy666]],
		["gift_award"]=[[元宝#30000|三倍经验卷#3|金刚石#100|五彩石#100]], 
	},
	[7] = {
 		["key_name"]=7,
		["gift_key"]=[[xmru43]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[8] = {
 		["key_name"]=8,
		["gift_key"]=[[cfz8v6]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[9] = {
 		["key_name"]=9,
		["gift_key"]=[[47eykr]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[10] = {
 		["key_name"]=10,
		["gift_key"]=[[4kw3s3]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[11] = {
 		["key_name"]=11,
		["gift_key"]=[[s25tab]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[12] = {
 		["key_name"]=12,
		["gift_key"]=[[h8vf3w]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[13] = {
 		["key_name"]=13,
		["gift_key"]=[[f753p5]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[14] = {
 		["key_name"]=14,
		["gift_key"]=[[5x62v6]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[15] = {
 		["key_name"]=15,
		["gift_key"]=[[tv36tc]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[16] = {
 		["key_name"]=16,
		["gift_key"]=[[74xzt7]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[17] = {
 		["key_name"]=17,
		["gift_key"]=[[wnjeck]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[18] = {
 		["key_name"]=18,
		["gift_key"]=[[xdnaa3]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[19] = {
 		["key_name"]=19,
		["gift_key"]=[[xsww33]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[20] = {
 		["key_name"]=20,
		["gift_key"]=[[jf8z4v]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[21] = {
 		["key_name"]=21,
		["gift_key"]=[[xtvy2b]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[22] = {
 		["key_name"]=22,
		["gift_key"]=[[hsraxf]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[23] = {
 		["key_name"]=23,
		["gift_key"]=[[dmv5d8]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[24] = {
 		["key_name"]=24,
		["gift_key"]=[[3fsdxw]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[25] = {
 		["key_name"]=25,
		["gift_key"]=[[envs8z]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[26] = {
 		["key_name"]=26,
		["gift_key"]=[[f5m7bs]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[27] = {
 		["key_name"]=27,
		["gift_key"]=[[nvyfxy]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[28] = {
 		["key_name"]=28,
		["gift_key"]=[[t2nvhx]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[29] = {
 		["key_name"]=29,
		["gift_key"]=[[4r3wsm]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[30] = {
 		["key_name"]=30,
		["gift_key"]=[[w4ssw5]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[31] = {
 		["key_name"]=31,
		["gift_key"]=[[j7vxun]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[32] = {
 		["key_name"]=32,
		["gift_key"]=[[2kp7ns]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[33] = {
 		["key_name"]=33,
		["gift_key"]=[[ezfzev]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[34] = {
 		["key_name"]=34,
		["gift_key"]=[[z3m2pe]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[35] = {
 		["key_name"]=35,
		["gift_key"]=[[rk3wec]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[36] = {
 		["key_name"]=36,
		["gift_key"]=[[n8uzar]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[37] = {
 		["key_name"]=37,
		["gift_key"]=[[zjw26c]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[38] = {
 		["key_name"]=38,
		["gift_key"]=[[2zbj8h]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[39] = {
 		["key_name"]=39,
		["gift_key"]=[[dx4cvu]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[40] = {
 		["key_name"]=40,
		["gift_key"]=[[tu7jbs]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[41] = {
 		["key_name"]=41,
		["gift_key"]=[[4edujf]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[42] = {
 		["key_name"]=42,
		["gift_key"]=[[wethxd]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[43] = {
 		["key_name"]=43,
		["gift_key"]=[[ckpcza]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[44] = {
 		["key_name"]=44,
		["gift_key"]=[[88zm25]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[45] = {
 		["key_name"]=45,
		["gift_key"]=[[27xjsa]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[46] = {
 		["key_name"]=46,
		["gift_key"]=[[6mkevy]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[47] = {
 		["key_name"]=47,
		["gift_key"]=[[5vdpe2]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[48] = {
 		["key_name"]=48,
		["gift_key"]=[[r2bdme]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[49] = {
 		["key_name"]=49,
		["gift_key"]=[[3rpv5e]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[50] = {
 		["key_name"]=50,
		["gift_key"]=[[d52ef4]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[51] = {
 		["key_name"]=51,
		["gift_key"]=[[yst48b]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[52] = {
 		["key_name"]=52,
		["gift_key"]=[[6j7whu]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[53] = {
 		["key_name"]=53,
		["gift_key"]=[[86fsjz]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[54] = {
 		["key_name"]=54,
		["gift_key"]=[[z4s33n]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[55] = {
 		["key_name"]=55,
		["gift_key"]=[[66my2m]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[56] = {
 		["key_name"]=56,
		["gift_key"]=[[jsysh8]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[57] = {
 		["key_name"]=57,
		["gift_key"]=[[7mkkd4]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[58] = {
 		["key_name"]=58,
		["gift_key"]=[[h3y6uh]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[59] = {
 		["key_name"]=59,
		["gift_key"]=[[2ryakb]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[60] = {
 		["key_name"]=60,
		["gift_key"]=[[um66k5]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[61] = {
 		["key_name"]=61,
		["gift_key"]=[[ktfcyv]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[62] = {
 		["key_name"]=62,
		["gift_key"]=[[5fx6bu]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[63] = {
 		["key_name"]=63,
		["gift_key"]=[[e3pay4]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[64] = {
 		["key_name"]=64,
		["gift_key"]=[[eftrjr]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[65] = {
 		["key_name"]=65,
		["gift_key"]=[[5f753v]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},
	[66] = {
 		["key_name"]=66,
		["gift_key"]=[[wb6b2p]],
		["gift_award"]=[[直购点#200]],
		["limit"]=1, 
	},  
}
 return config;